# Pre-encryption placeholder. Steps:
#   1. CF Zero Trust dashboard -> Networks -> Tunnels -> Create a tunnel
#      (Cloudflared connector type, name: lewelly). Copy the tunnel token.
#   4. In CF dashboard for the tunnel, add Public Hostnames:
#        jellyfin.lewelly.com -> HTTPS https://traefik.traefik.svc.cluster.local:443
#          (originServerName=jellyfin.lewelly.com, TLS verify on)
#        ha.lewelly.com       -> HTTPS https://traefik.traefik.svc.cluster.local:443
#          (originServerName=ha.lewelly.com)
#        auth.lewelly.com     -> HTTPS https://traefik.traefik.svc.cluster.local:443
#          (originServerName=auth.lewelly.com)
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-lewelly-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:rj/Q++2F6ltzPUxFE3ljztlQfB+zOK5gmg7ZwT0UwSPIYV6el4tNIRTIKFkSGqAjD5Oo0L3/+TDzYR/6X1FfyEv9sE5uBHdJezdcNW5l4ZrXdYr31U94L47PdX1RWjPvApPmj6Fr1jDsvbPx7vpjJ2/nXHLT+xnRXIuOUIwtxfhM9aUYWv/5iXGCbHUkaC6HrK4JoyqODVQByoSHKyiHvQB9q+ahO1vtNz/cKQCGec56VYOtY6BMIA==,iv:cjtCexon3X8gldoig1v4dKYdeXleHnkdM0WLENfB4BE=,tag:mBW7Q6JCwkM6bb6kZwntPA==,type:str]
sops:
    lastmodified: "2026-05-28T23:08:39Z"
    mac: ENC[AES256_GCM,data:sormBgBFMg6KaRSIi0MQCuqURbL4dHoh9Y1Oy77uAhKqjHjc7BPMo7wre72vOKK4o/3yfzFBjipA+h59HIGz2bdmIIBQWdQ2v2TO3QGpH7pPCbyfknLOs2EfLzLvkPrRQmKRy/FoDG7qn2CDHNvp0tA8rATjSBexSS3dBQb8J84=,iv:vG0aSs0+AWAj4BrpB4SMr1lCSkBjFhvIKr3xVXGYD00=,tag:9gEeDM/ftr+bnh9r0RH1Mw==,type:str]
    pgp:
        - created_at: "2026-05-28T23:08:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAJGkxSd0xXLeYOeZoDboTuEMFCPrEGu0Lnpk/X4jwdzcw
            MzwRxEw8yV+4pKHCreT6T6EsyHmZqB9G59X5A9stzcs3Qjij7Bq2t2CDrRUD9oIt
            1FsBCQIQcIQPcIpStz9vCasIW3xwpZE7/akrsfqszEr6ow0OvBzgQuwVQeI3DKX5
            7g+rO5vUNV+GvY7j3Zo6MwivDqL7pOe1NamcQa0TM5SAvk2hNQbujSd+8Rkt
            =VYpT
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
