---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: esgpull-sync
  namespace: climate-ref
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 86400
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          initContainers:
            - name: install-esgpull
              image: python:3.11-slim
              command:
                - sh
                - -c
                - mkdir -p /tools/bin && pip install --no-cache-dir esgpull -t /tools/lib && cp -r /tools/lib/bin/* /tools/bin/
              volumeMounts:
                - name: tools
                  mountPath: /tools
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                capabilities:
                  drop:
                    - ALL
          containers:
            - name: esgpull
              image: python:3.11-slim
              command:
                - sh
                - -c
                - |
                  set -e
                  export PYTHONPATH=/tools/lib:$PYTHONPATH
                  export PATH=/tools/bin:/tools/lib/bin:$PATH
                  export ESGPULL_INSTALLS_PATH=/esgpull

                  # Initialize esgpull and add queries on first run
                  if [ ! -f /esgpull/installs.json ]; then
                    echo "=== initializing esgpull ==="
                    esgpull self install /esgpull/data
                    echo "=== adding queries ==="
                    sh /scripts/setup-queries.sh
                  fi

                  # Ensure index node is up to date
                  esgpull config api.index_node esgf-data.dkrz.de

                  echo "=== esgpull update ==="
                  yes y | esgpull update --yes

                  echo "=== esgpull download ==="
                  esgpull download
              env:
                - name: ESGPULL_INSTALLS_PATH
                  value: /esgpull
              volumeMounts:
                - name: cmip6-data
                  mountPath: /data/cmip6
                - name: esgpull-data
                  mountPath: /esgpull
                - name: tools
                  mountPath: /tools
                - name: tmp
                  mountPath: /tmp
                - name: scripts
                  mountPath: /scripts
              resources:
                requests:
                  memory: 1Gi
                  cpu: 250m
                limits:
                  memory: 4Gi
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                capabilities:
                  drop:
                    - ALL
          volumes:
            - name: cmip6-data
              persistentVolumeClaim:
                claimName: climate-ref-cmip6
            - name: esgpull-data
              persistentVolumeClaim:
                claimName: climate-ref-esgpull
            - name: tools
              emptyDir: {}
            - name: tmp
              emptyDir: {}
            - name: scripts
              configMap:
                name: esgpull-queries
                defaultMode: 0755
