---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: esgf-fetch
  namespace: climate-ref
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 86400
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          initContainers:
            - name: install-deps
              image: python:3.11-slim
              command:
                - sh
                - -c
                - |
                  mkdir -p /tools/bin &&
                  pip install --no-cache-dir \
                    intake-esgf \
                    typer \
                    attrs \
                    loguru \
                    -t /tools/lib &&
                  cp -r /tools/lib/bin/* /tools/bin/ 2>/dev/null || true
              volumeMounts:
                - name: tools
                  mountPath: /tools
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                capabilities:
                  drop:
                    - ALL
          containers:
            - name: fetch-esgf
              image: python:3.11-slim
              command:
                - sh
                - -c
                - sh /scripts/run-fetch.sh
              env:
                - name: HOME
                  value: /tmp
              volumeMounts:
                - name: cmip6-data
                  mountPath: /data/cmip6
                - name: tools
                  mountPath: /tools
                - name: tmp
                  mountPath: /tmp
                - name: scripts
                  mountPath: /scripts
              resources:
                requests:
                  memory: 1Gi
                  cpu: 250m
                limits:
                  memory: 4Gi
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                capabilities:
                  drop:
                    - ALL
          volumes:
            - name: cmip6-data
              persistentVolumeClaim:
                claimName: climate-ref-cmip6
            - name: tools
              emptyDir: {}
            - name: tmp
              emptyDir: {}
            - name: scripts
              configMap:
                name: esgf-fetch-scripts
                defaultMode: 0755
