---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama-mole
resources:
  - namespace.yaml
  - endpoints.yaml
  - exporter.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
