---
apiVersion: v1
kind: Service
metadata:
  name: ollama-mole
  namespace: ollama-mole
  labels:
    app.kubernetes.io/name: ollama-mole
    app.kubernetes.io/component: exporter
spec:
  selector:
    app.kubernetes.io/name: ollama-mole
    app.kubernetes.io/component: exporter
  ports:
    - name: http
      port: 11434
      targetPort: proxy
    - name: metrics
      port: 9400
      targetPort: metrics
