---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ollama-mole
  namespace: ollama-mole
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama-mole
      app.kubernetes.io/component: exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
