apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: hermes
stringData:
    #ENC[AES256_GCM,data:4KYRrxDk0kFi/x3zzVqCkvlpUn7Tuhs/x+cShNUaCqN70QR5AtBIrN37gPbVJuwDJfhr4qkARe6oTOGd9WY8yHA=,iv:5pQZksMhP1Lei6+rh4uvYkzAKApBSVtN2k8sz2zqs5o=,tag:wlrZ4RsDefsWJ27Sgnzzog==,type:comment]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:LzwkzqdaZOvqaLB4dluq1SJkxvufg2Gu7MPOR0z6wEplnrQEnts9oudfBWEosGH7igqnL1OQu0e+f3DwlgQk4rDcAeKwHiZU,iv:wW9D2A1yniR2KWiANzEIJXu98MNYeuzL7X/bIXboGQQ=,tag:ATw80D3sfXnj2G8o3FEhhw==,type:str]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:sMn8vzfHhBoSB29jXfRAL2WZ,iv:6RflXpyiuNmtCTSNG/wYZEi1gHJ7edm8VzrqH/WM558=,tag:62TyD5R0MWuxuoUL1aV+/A==,type:str]
    DISCORD_ALLOWED_CHANNELS: ENC[AES256_GCM,data:ttmLXjMa52h6Zd7Kh2uWO0IyvA==,iv:V62wNBrRNf9QeyNTas8edouWSYFFiEdcs6pcMeSbQI8=,tag:NlSF+8sX2/x8dAh/18QNrA==,type:str]
    #ENC[AES256_GCM,data:pReSCut8LQ==,iv:ppJ2/8OP/pbNp64k8Rlis7gSfrvhW1U3oX88f1ktcVI=,tag:uBegBS5vXXlaubiNrtsTlw==,type:comment]
    GITHUB_TOKEN: ENC[AES256_GCM,data:Bq7kthwEk+VEwCTdG+zT6gPs+ke16N3v9AKdmiMnE4bfYX4duVl5oqkI4/Wg6hFVeL6ilTuw0jLEGHsis7umphB43If7HD/hdcUy7JjDVb2CrmWX16efIz+zyGjB,iv:SwfTIpf8xFXyhfnjk3yP6Z+TGikagHPeE9ktelZBcZo=,tag:anVyTjdahCmh9dGmMhWNqw==,type:str]
    #ENC[AES256_GCM,data:MDbVQamX5MC4t19e2Ksv3Je/,iv:cqF9VCsV/2DTYTSXagkP5Bn7U0WDywX1fGuQOxR8DZ4=,tag:5E78ICSWdaXUxziTByTpdw==,type:comment]
    BWS_ACCESS_TOKEN: ENC[AES256_GCM,data:TkPtotKCWsBSlwIbwIuCCHymug6V4yLSihTcLOIgSP53laUeEfM+KrG5L8EvMz/abh1eMSdcjqWxCxBDNux8XYHlkTp7x/XBCZo4Nz5y7wkL+eVR4qT5bbLWLGJyGA==,iv:+FVM7Yd+USqSfBI2o1V/Z5cgoH5+NERQABVAFF3HQmk=,tag:xz5WnDZjVvxSDjywprkEKw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T03:14:29Z"
    mac: ENC[AES256_GCM,data:4Kc3/IzcWW3R2AALux1w89y6lzWjPwrbyYPEcZB9jeYB3QUw/WqcoYfcZSfAb0vxY0dZ+cUnNQYbY8B4ST3NxIf4Q+6YFCez74HWKakCj2xEOOcPeMIe5YPFzx5D8LFL/yOs5xO3yp0uv1QTcNYVj5FN+ppmmkIA0/6Uv8RVKA4=,iv:8M9WjC2Dwbz7RaCT4z4G1/4b+hqThbVDLjtmIc+d538=,tag:sGglH8vKQfQ93G8dBToBPQ==,type:str]
    pgp:
        - created_at: "2026-06-19T09:34:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA+h7G4cc7hAba9jFoN2Ba4uUWhtKyW/kNJ1K5ELq7yE4w
            XuK8iqpg369uXfoQS4jkRfDrF1BOsAA3Ftl/DAZEKV4rMSetRklYeKalDEl8smAK
            1GgBCQIQBiywEpIMb+iw0BmDyFAwxgHZlXBY2wXXfGP50+H54j2HE0d4XLGkq9cI
            Y6b0JM3jriIYpemZAAtkYjL8iNq2wqDooAvGYNjjKGUBbuiybUvY+2wHr6/TA8OS
            dPh4ayfTeAKb+w==
            =jxlU
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
