apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: hermes
stringData:
    #ENC[AES256_GCM,data:n/EnAyqQVyGkz9jVFwPr6+y46CbBOGNwC06PDyOz9SzBRkKPMz0R1VJp4nKdtRnoIHMCgv9iUU9qCWuirw==,iv:Nyh5crKtvNUdDJ70V271V4FFoOn3NnQ9QgMiRruIGu4=,tag:4+ZUvjj0Ia/aMpYCGKyzCg==,type:comment]
    OPENAI_API_KEY: ""
    KILOCODE_API_KEY: ""
    #ENC[AES256_GCM,data:4KYRrxDk0kFi/x3zzVqCkvlpUn7Tuhs/x+cShNUaCqN70QR5AtBIrN37gPbVJuwDJfhr4qkARe6oTOGd9WY8yHA=,iv:5pQZksMhP1Lei6+rh4uvYkzAKApBSVtN2k8sz2zqs5o=,tag:wlrZ4RsDefsWJ27Sgnzzog==,type:comment]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:33tk3V6ikYLEqQ==,iv:ibrBahJquZHG6vz2Xlmoy/HsMtvTMVVdX19Ug5zuc2A=,tag:+Xc4O93Da47LhfFl+f9KVw==,type:str]
    #ENC[AES256_GCM,data:i0R8zo8+SxYRSwUtgdEEKMDscnvCXgKFVKLzmhdpn+ZMsz5tqL9EzecO1bUlFBOEkvUfd8HpnMM2RA==,iv:IY9cuz2hYSHFvW5JNRRz40uoitDUkueYrZrhLWW4S5Y=,tag:QURqTfsGZl2vrkFmfPcFJA==,type:comment]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:2XD+iHirgVTpzw==,iv:JxkVIL8M1UcKj24eMuEq+LasNpEznT5r5w/QbkQATFU=,tag:WtPTgQ+pF/YM14ik+u+wcA==,type:str]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:6IrhieTsaspl4A==,iv:6vG7/RdZ7UyFVRrlEZb40nMsGZ122t1E8uupJc4Vwgo=,tag:jp0AP9SY/n84Dcn1Uu+AGw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T02:56:15Z"
    mac: ENC[AES256_GCM,data:kHyneQbniMCZl5XC4NgPBugZe6Rp/EmssrhU3gCnB3+cYxzfu2Zwhk3uBBBCseR1B+VSEtogzOPTSV60HgYUK30gUnz2llCTnYzloKdGvUomMQTmKfawi1WGJVCtbFh7G1F2jy6GUrvyikB9BqMZ2pUddHhm6cg8KTk6mzKIJR8=,iv:NodeuzA9MV8J6OaBeh99u2oflPXGMKlbAVldJj3xG+c=,tag:jqwhrJTtjc35/0Bhm7w8vA==,type:str]
    pgp:
        - created_at: "2026-06-19T09:34:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA+h7G4cc7hAba9jFoN2Ba4uUWhtKyW/kNJ1K5ELq7yE4w
            XuK8iqpg369uXfoQS4jkRfDrF1BOsAA3Ftl/DAZEKV4rMSetRklYeKalDEl8smAK
            1GgBCQIQBiywEpIMb+iw0BmDyFAwxgHZlXBY2wXXfGP50+H54j2HE0d4XLGkq9cI
            Y6b0JM3jriIYpemZAAtkYjL8iNq2wqDooAvGYNjjKGUBbuiybUvY+2wHr6/TA8OS
            dPh4ayfTeAKb+w==
            =jxlU
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
