---
apiVersion: v1
kind: Namespace
metadata:
  name: hermes
  labels:
    app.kubernetes.io/part-of: home-infra
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
