apiVersion: v1
kind: Secret
metadata:
    name: volsync-secret
    namespace: hermes
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:W2ph6f8vIZ/acCh05g4SWM8SMQAd7QvazIq51g==,iv:f7xczhooJxdbwxC2swBJJQA9XDcMdGOR4PUycPIvp/s=,tag:9tY426tjpJmcKDImNAWkaw==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:6Y7ogKuU2XBkIlfxpKHMddhzMDxIu78jOFSaz/a1A4257AN6wNA01eRgU98=,iv:majTFJef1zZg+xUbVdd9iqQbPoRcEY2F06nrlvlLRHU=,tag:JoFy7vW9z4bgod/0S3DY2w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T02:32:48Z"
    mac: ENC[AES256_GCM,data:VWvGpVFOuJIkA07quJsVmBNPDLA7kVNTylIjJMQ+lJCYDJ7p/s6KIfw/koGzTQ+0SkNv08wbVxPPVmkr1TXNLcoJGNxNhRSy8AIBma9ykDNf1rbgRU3EPTfxdTj87knB65WWOTcGV31P9UyNRsntipW2P4pvJjQ+PyebqmG9ciI=,iv:YzL9ERc57cw3la85OU6EYYF9LnsOYFqvkAYP0mS8EnM=,tag:NUhfdEaBut3OAlBD5CILiw==,type:str]
    pgp:
        - created_at: "2026-06-30T02:32:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAWrPHyFu/9S6LkudWruGCUaigoE2lULJ+sRcWtItCo2Aw
            yYWSgtMKSp45FC0QKPp7PIX+7a0GBpxe4JdmgK9E/pBhCxiRJhtafGnSXasRzyhP
            1GgBCQIQmJbYZkO6Txek+xjgVgr+tIkd7ewjZbiKzAQ+s9pkHWz1Y4FRYxF4up+v
            u0/8LL6FE+fImxvEJvbZXU2XrJ2bcc/u0GjqnAZ+5OH8uP8nhoD1kf8yQlCv8fYp
            fOL5wvAvKAzV+w==
            =v6Fd
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
