---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyseerr
  namespace: media
spec:
  parentRefs:
    - name: home-gateway
      namespace: cilium-gateway
      sectionName: https
  hostnames:
    - requests.home.lewelly.com
  rules:
    - backendRefs:
        - name: jellyseerr
          port: 5055
