apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:pKxSWfGmrK1JVEFswn5Z5h2qCK97XsPPeBSwhdsWnOS0T7S2GuqNBrEeoISJqD5+LwsjakfAePKyB7/Ds3WSoJ5479W7eJzRudmvrFvkNkuLGYeCh/cGQSbojHZRjw18,iv:shv6ajvgygcuJlAMVuweVucWfndFCArV1jR2iqjPpLQ=,tag:1+JNN8rEZKkKzenOpmHRnw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T02:23:57Z"
    mac: ENC[AES256_GCM,data:7F17S1hIeliyu+YxqG0Dfu3C55sDKHmudAWaVsNiEbj3Lcs04uVevRqjrAD24RYVbyBW2C4/pWlIPv15TDC4temNatbBooQk/BKcTRdfCV06tAmXRNpiftVweJPTeqpUKo7eWCWw3qPcCxLx0xg6wrfPsoXOytgfz8x+PRwlaYA=,iv:PqMmf3QcfNny8KKrP2Hiikk3MOk9YzSRRsbqBHdWzd8=,tag:H5XUsKva/ai1BklVzJtiVQ==,type:str]
    pgp:
        - created_at: "2026-04-13T13:17:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAx98GzBhIQneS0TDhrcelf8rbK2XS1C8CctU9MiEX22Aw
            5my84flU6NOKnGIdcxmB+lG2vJfCY475qXix3VdEJRFVYbvAaBnWe2wkqPLpXnyF
            1GgBCQIQW7WrN/bVWwo8uSfUjUgUC9lZ1zAHC7Om2sE0RATJRwfl2kSi6SU4n/Ii
            pB82OuiXfBgwY/pOpjdqGhc1V766AhHCidpfIKrYIX3+Sqj23O0GXEaEqBf/BTwg
            05l+5fbmr5CwVw==
            =yh4M
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.2
