apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:cbBF7f3RgCMdM7GadeLMbBIH66PE8lxwJZP3pNksoslzLBKCdc36H1GAXEsZs4wIzlI2J26y/JKKzicdeFU9RggITH8NfJdvQ31MZBi1Ayhi3j7Ta2nyDRoTfyg+ZA==,iv:bBN9bqIhMZP+bZEgdFVE6F8yv91k/55HqWQ5+dmsxSg=,tag:xseNJou9+KlWUSzb6p+5OA==,type:str]
sops:
    lastmodified: "2026-04-13T13:17:52Z"
    mac: ENC[AES256_GCM,data:ckoVUF6fjGvHXkdFXjuO/gek8wLuVtLiAcTQnCL53ksP72tnZuxLHZeTj7qJo41NiMdECqHS9hwx4oLf+hkpN9nADwbl+ASmeDZbhlkt+fKEbt6Oua70b7ay7DCyd4IfzetKJbaoA/MUWlnemSV0l6LQ7eCNZtr4zCEjqkI9Hxw=,iv:E6JQyQO4R0N0YatDGRXreuniiHMCW3aN//z4/xJopVU=,tag:0eBbitDFmFDYTxEYWEcWaw==,type:str]
    pgp:
        - created_at: "2026-04-13T13:17:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAx98GzBhIQneS0TDhrcelf8rbK2XS1C8CctU9MiEX22Aw
            5my84flU6NOKnGIdcxmB+lG2vJfCY475qXix3VdEJRFVYbvAaBnWe2wkqPLpXnyF
            1GgBCQIQW7WrN/bVWwo8uSfUjUgUC9lZ1zAHC7Om2sE0RATJRwfl2kSi6SU4n/Ii
            pB82OuiXfBgwY/pOpjdqGhc1V766AhHCidpfIKrYIX3+Sqj23O0GXEaEqBf/BTwg
            05l+5fbmr5CwVw==
            =yh4M
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
