---
# ServiceAccount for Technitium DNS to read TLS certificates
apiVersion: v1
kind: ServiceAccount
metadata:
  name: technitium-cert-reader
  namespace: cilium-gateway
---
# Role to read only the TLS secret
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-secret-reader
  namespace: cilium-gateway
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["home-gateway-tls"]
    verbs: ["get"]
---
# Bind the role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: technitium-cert-reader
  namespace: cilium-gateway
subjects:
  - kind: ServiceAccount
    name: technitium-cert-reader
    namespace: cilium-gateway
roleRef:
  kind: Role
  name: cert-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
# Long-lived token for the ServiceAccount (for external use)
apiVersion: v1
kind: Secret
metadata:
  name: technitium-cert-reader-token
  namespace: cilium-gateway
  annotations:
    kubernetes.io/service-account.name: technitium-cert-reader
type: kubernetes.io/service-account-token
