---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/headlamp/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: ">=0.25.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: headlamp
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    recreate: true
    cleanupOnFail: true
  values:
    # Replica configuration
    replicaCount: 1

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Ingress disabled - using Gateway API HTTPRoute
    ingress:
      enabled: false

    # OIDC Configuration
    config:
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: headlamp-oidc-secret

    # Service account
    serviceAccount:
      create: true
      name: headlamp

    # Pod annotations
    podAnnotations:
      app.kubernetes.io/part-of: home-infra
