---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/headlamp/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: ">=0.25.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: headlamp
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    recreate: true
    cleanupOnFail: true
  values:
    # Replica configuration
    replicaCount: 1

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Ingress configuration
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: headlamp.home.lewelly.com
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: headlamp.home.lewelly.com
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: headlamp-tls-secret
          hosts:
            - headlamp.home.lewelly.com

    # OIDC Configuration
    config:
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: headlamp-oidc-secret

    # Service account
    serviceAccount:
      create: true
      name: headlamp

    # Pod annotations
    podAnnotations:
      app.kubernetes.io/part-of: home-infra
