apiVersion: v1
kind: Secret
metadata:
  name: volsync-secret
  namespace: media
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:HMPxXZTspqKJYMe/j/Qbuc4rLUaJPZdbYKlbZXpiKKCVE4LoXAa+8tAC+nY=,iv:9Hs9jvbo2/UnMLpnq1Aw0Pp17k2CVRnpLd6xeyRhYN8=,tag:Mqm0b5X+SI3mqutMGYmYpA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:8+s4HWCVLfre1CQ9AdIeGx9JfJBcTifiQ2Oc8Q==,iv:jBNmQbgFJ9VoNfCMDn9fYK48EAfJEkBcKmgGpbzH4lA=,tag:i5AQNX/4ShAarPFH0G3XfQ==,type:str]
sops:
  lastmodified: "2026-04-05T23:51:44Z"
  mac: ENC[AES256_GCM,data:NQ7bu/ysIwDpIWCJUsND44QuXH5T6O6mDHTxmBz9my/h/Fpz117dER/43YpcWEfKPszBUKiw6jbPMSkVfKI9qIz2fL2s20cS6gr7c1zk7Mns7UjSMZ4ftaPT2UFJTFHTYTQrQbYZJTL7c9Gn9Rb/CrKQ4KXzop1j0/QXkaUisKw=,iv:dqDIunNL3e8YH/qF5+mRWpnbhlmbh1dAK2t/08PY5r0=,tag:prAAL7amc55lAW4FED6aIw==,type:str]
  pgp:
    - created_at: "2026-04-05T23:51:03Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAdvK0oGoSMxcMfd2nKlVgHasZ2tcd5vyl/7x5GIn5x0ow
        j2ZPI86CisIcMxJT1ubcWi/fJEzVaNVEhjS1sRDvH5TeDsMa8N0AcMt9PkGQz3zZ
        1GgBCQIQO3oasuI+Amy9u0Q5PEK/xaqM+sxA4LR7EN7nxJvGuCtwvBTMuRqFljH8
        O70MwsqFxX5izve/SiiNwEGyUTKLcQJ6ojGITUCp0TzXj6Z3qT5R3YeBl0CEEfIS
        YFDhqK03grNYDw==
        =dxkE
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
