---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 24h
  url: https://charts.authelia.com

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 30m
  chart:
    spec:
      chart: authelia
      version: ">=0.9.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    recreate: true
    cleanupOnFail: true
  values:
    # Pod configuration
    pod:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      extraVolumes:
        - name: users-database
          secret:
            secretName: authelia-users-database
            items:
              - key: users_database.yml
                path: users_database.yml
      extraVolumeMounts:
        - name: users-database
          mountPath: /config/users_database.yml
          subPath: users_database.yml
          readOnly: true

    # Ingress configuration
    ingress:
      enabled: true
      className: nginx
      certManager: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: auth.home.lewelly.com
      tls:
        enabled: true
        secret: authelia-tls-secret

    # Authelia configuration
    configMap:
      theme: dark
      default_2fa_method: totp

      log:
        level: info
        format: text

      authentication_backend:
        password_reset:
          disable: false
        file:
          enabled: true
          path: /config/users_database.yml
          search:
            email: false
            case_insensitive: false
          watch: false

      session:
        cookies:
          - domain: home.lewelly.com
            subdomain: auth
            default_redirection_url: https://auth.home.lewelly.com
            name: authelia_session
            same_site: lax
            expiration: 1h
            inactivity: 5m
            remember_me: 1M

      storage:
        local:
          enabled: true
          path: /config/db.sqlite3

      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt

      # Access control
      access_control:
        default_policy: deny
        rules:
          # Headlamp access
          - domain: headlamp.home.lewelly.com
            policy: one_factor
          # Auth portal itself
          - domain: auth.home.lewelly.com
            policy: bypass

      # OIDC Provider Configuration
      identity_providers:
        oidc:
          enabled: true
          jwks:
            - key_id: 'main'
              algorithm: 'RS256'
              use: 'sig'
              key:
                path: '/secrets/authelia-secrets/identity_providers.oidc.jwks.RS256.key'
          clients:
            # Headlamp OIDC Client
            - client_id: headlamp
              client_name: Headlamp Kubernetes Dashboard
              client_secret:
                path: '/secrets/authelia-secrets/headlamp-client-secret'
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://headlamp.home.lewelly.com/oidc-callback
                - https://headlamp.home.lewelly.com/
              scopes:
                - openid
                - profile
                - email
                - groups
              grant_types:
                - authorization_code
              response_types:
                - code
              response_modes:
                - form_post
                - query
              userinfo_signed_response_alg: none

    # Secret configuration
    secret:
      existingSecret: authelia-secrets
      additionalSecrets:
        authelia-secrets:
          secretName: authelia-secrets
          items:
            - key: headlamp-client-secret
              path: headlamp-client-secret
            - key: identity_providers.oidc.jwks.RS256.key
              path: identity_providers.oidc.jwks.RS256.key

    # Persistence
    persistence:
      enabled: true
      storageClass: rook-ceph-block
      size: 1Gi
      accessModes:
        - ReadWriteOnce

    # Redis dependency (lightweight session store)
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
