apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:lZavs6ZyTyxXdmhpu8sJgYoGWmRek+xh,iv:XlPFIuERzgK0FYzboe/1ttvet2/xiq7Uj3OnsbQOHOg=,tag:ULH1C79kfeOT5N+O2U74nA==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:/CXc41cfdMSfOmaE2fSkHbaA9qzF/rLA,iv:DMV7iIYernwhmXZGO1ukSXc72IfSs47RveYvVac85AI=,tag:5NGkFOAB/6gZv3XFMdA+xw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:tEQiZ9guFYL3o93u6TPmu9jXIL0pecFT6jw9SmowiYLZr5IUxM3kakJmh5k=,iv:X9NJgy6uN6FrYAtdYglOfD+31PNH7MCSqDJyuOJgKYc=,tag:M0QWwfvrvQN+K6RjK7YjgA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T14:37:52Z"
    mac: ENC[AES256_GCM,data:s0HCFLxOfoITrhCpqRUowN8kZVViqpUWkSrQDiZnd01U438HM0mF8sWyhcFni5RVUb20qYkKgRV+mf7IsBZ34wsyNRVcH6Hdrcz9ThHbX4WwHgNyjepJMM9DwZWGs2BALVbQhRW/FrQtIceNRiBFPs9JrH6lnpaEr8lmvIkjkEM=,iv:iuG2HIecFAILx5UElOCe+a5t/LqeTUlmw5hvTWrGDP4=,tag:IhlANq7vKD+f2HCuQ6q0eA==,type:str]
    pgp:
        - created_at: "2026-08-22T14:37:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA/+UDZDqW5y5Io344lTcui6yD+Daz1maX60yJVEFTgj8w
            nJNn3RxrBl3/v4ds35gpRLYV/EhHvApmExwF4a/Tz8Xakt8vHArNQ+N95QxOJ4Ds
            1GgBCQIQEQHZLbLTHw8fDccTJ0hjc6QiyHIbg+k8Cw4ayA/P/AtjozWKSWVSm065
            KKPMfnY2k6TzOxhFlprmxLzzDbKAeqgQrj7tIjp4Z8hpak3Aa/h1/n8m9OJtE+SW
            kOW/8x9//txKHQ==
            =qIoC
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.2
