---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${VOLSYNC_CLAIM:=${APP}}
spec:
  sourcePVC: ${VOLSYNC_CLAIM:=${APP}}
  trigger:
    schedule: "0 16 * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=3000}
      runAsGroup: ${VOLSYNC_PGID:=3000}
      fsGroup: ${VOLSYNC_PGID:=3000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/backups/k8s
            server: 10.10.20.20
    parallelism: 2
    repository: volsync-secret
    retain:
      daily: 7
    storageClassName: rook-ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
