# SeaweedFS S3 IAM identities. Loaded by the S3 gateway via
# `-config=/etc/sw/seaweedfs_s3_config`. Replace the placeholder keys
# with real values before encrypting with sops.
#
# Format: https://github.com/seaweedfs/seaweedfs/wiki/Amazon-S3-API
#
# To rotate keys:
#   sops apps/production/storage/seaweedfs/identities-secret.sops.yaml
#   flux reconcile helmrelease seaweedfs -n seaweedfs
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-identities
    namespace: seaweedfs
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:DhsVb1P27p0B9dJwtE/dZl5a9qxdZIDkSJSTmBuCSaRg94KjsHGyYWRwpewNJ4w0J/+cNceRZ0WL/7cfwWfuFGes56xeqDHpgbdd/klTv71v3IJZGp134F42YN2bCKzwmbRS/kbZJIolG8mxuRKktwd7+79WoI2OI+YRYxSMuHvS2mZ3+9ZIUZKOlL9Wpv1dLtWb+Qd97FbXYXS4K4s1cNNMdpVyZImhZvPdKa1c+4LvBUgUFhplgkzB6sMZBqk0jTvsd6FrA6rxCz+bSe3pCHRDuXCKB+cA7+NzFIPEwK7Y/jqqc8oLSwWULplKnUUmbbvIfQdf86yYWzidMydp9mAaFgozr46a637/giRNRc3Sfv0L5MqCI1msU8v6+htcrxkobtvFyW/W94FiT2Vu8qw1Bg3wbhzGNCoMymxwqKWWjBEebmKSFksweklgGMW1YzULX6RSsPVv6Kd3e3ik1QHgAlnyzpnqxWh7V8A1pS2XK0cSkd3N9lpEIexi/gt2oX1ktpL8W1kG8aW+w60RpGWghb0nQ4q+AmfIuEMV7XfYtTi8oshg7BpTeiAYozC89IyyLjb/tHX0cXcp6kbUwKy1dyWfCANXf5QdatWf2ty64Ew/hTm5HC3NJHk2NTkmag0iPy1U2Z/v/fLeur8NGgc8fwSnPENWtKtemKgfb5tO9iKyH4cQwkffWe40Z3oTP1/pLqK41diHm3slGd7OSRXzyniH0u2jnBQGcrft0NL14kaFK5Z0+U7U4xJ5BTQxfOLsjZcuMdambCfSFF9v6t/RhO74lgzhFNFqmgHPOfBc7Sn2C5rRG86WSpH0p039NDRnawRWXr081/Ak+Q9aBlqyxETXP4KqScElmMatiaul/uyo14IM1uKWnlyrx4ZgohBLutHYi33zGU/diMybjxZL3wOwkrshceLgscOicosGhWLK2lkCh3Q7QLBkQapAnm0V1Ot/Ch+sVruK584w7uoWCybC7x1lgPboKmWUMpqWPgwl//M=,iv:VyUX6yrVK4FB9xoztr1vGhwwzSptjsA67jvgE0zc8Xg=,tag:4m5SGiug8l/1b2uFkroHHw==,type:str]
sops:
    lastmodified: "2026-04-20T04:04:57Z"
    mac: ENC[AES256_GCM,data:H4fbKLgHScIg5PyNI2JEUwrta56gtt67ZJaXGygvnBsnWthX9dUa3idoR/n4W0XWCeuymfEaWGaO+EarYtR4TLtqQPrDFv/9C9BEt2k6mmCM1SaFSuctBH6p9211FqpNJjoNQi8v7QeILhomDSjUAYE19BU1WHdbCyBm+l+Bq/0=,iv:tCzG2oPh6Q+GJkK8BpWaPwmUFZtX9E6d73YP+3O33AI=,tag:QCqC6mHWwRTpVUmGTMPU5g==,type:str]
    pgp:
        - created_at: "2026-04-20T04:04:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAK2U92/CX21uSC/GaHZLCJH9/ByWBe3FPrPuztQgUtmww
            Ur8UkEV1tLASrXjGy3Qh1KsLhd53pMqOwQUgD/7smcETe/9+pTeqvtz6612vF2GB
            1GgBCQIQh89CVLt1U43Q67Z7dCzao7nv/7y0qeQ8twqIEngGOo3OGvMFdRAzeHp5
            DrtziN+gdLuKQAnFfop2AmvbioDnyb1hcaWOLomX8gsCm3vbgDP6IlztfdU2vHRN
            hbtHRcuCkg5l+A==
            =yqQp
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
