---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: github-runners
spec:
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-climate-ref
  namespace: github-runners
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: github-runners
      interval: 1h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    githubConfigUrl: https://github.com/Climate-REF
    githubConfigSecret: github-app-secret
    minRunners: 0
    maxRunners: 4
    controllerServiceAccount:
      name: arc-controller-gha-rs-controller
      namespace: arc-system
    template:
      spec:
        initContainers:
          - name: setup-cache-dirs
            image: busybox:latest
            command: ["sh", "-c", "mkdir -p /data/cache/datasets /data/cache/software && chmod 777 /data/cache/datasets /data/cache/software"]
            volumeMounts:
              - name: runner-cache
                mountPath: /data/cache
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ["/home/runner/run.sh"]
            volumeMounts:
              - name: cmip6-data
                mountPath: /data/cmip6
              - name: runner-cache
                mountPath: /data/cache
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: ACTIONS_CACHE_URL
                value: http://actions-cache-server.github-runners.svc.cluster.local:3000/
              - name: REF_DATASET_CACHE_DIR
                value: /data/cache/datasets
              - name: REF_SOFTWARE_ROOT
                value: /data/cache/software
        volumes:
          - name: cmip6-data
            persistentVolumeClaim:
              claimName: github-runners-cmip6
          - name: runner-cache
            persistentVolumeClaim:
              claimName: github-runners-cache
