apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: openclaw
stringData:
    #ENC[AES256_GCM,data:btcA7+4gMuItEfFLKSo9X1RdMQoMQ/Lv6CY0YviZpuSqvsRBDpm2uE5xa0I+AumJ4/eZEWz0VLA=,iv:3Uqg/Z3gOhuNjt8AeS1zgMNwmtpcbK98ybxfn41ayhw=,tag:knucqe1jBVijRkTJpwgURA==,type:comment]
    KILOCODE_API_KEY: ENC[AES256_GCM,data:MxJcVfC25LGhPq3/J6ISmkyPIn1oCH2k7cwcGfFIs9qW32oPn/+WV+O//nN+ZmB4tFY/leV36O6slFO33LyIGVh9hC70VhWPhsF2sdUELkpHs87QCNumHdA8bgvZ4ljsUJKYaNlVKUFrbWreeoiFK6BPjcE1YiU6EW2xBkuyJVZZfG2XivyO42lL1q6G6MpvRvwfOeq4vz0E3SZvo+RE52OulO0DcnRYUXQQLZ2Es9xeps+zQ2bRBlvomQ2EAS0DjHoHHixd0rUngKjQGUqJ5/4GzaBkenjSH57bPf9J/AU4+evHtw10ikWTL+tU5FkX1XjoOc4HxK6PY2wUgIoi7SqgyNNFwjHPoB/TPQ==,iv:xkEGs5U/kBY8mB/LDGF1ktKLbIr69kgptya8oRHH5sQ=,tag:EaBFl5NuS1Ot1MKL0Epm3Q==,type:str]
    #ENC[AES256_GCM,data:lAKbjhiYbb6fsJtqBmPKf0RFsU05z0ddEqyYvKKFEiBCK3pJcQ0udRKVjobBjwi6Bpcluw==,iv:B4V1IGhhfmgWaYO1PtEFioKCQlLTNzOJwKX4NRs5xDA=,tag:lLeUwu6aqFHdVmLDMRIhDQ==,type:comment]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:PRPfN9DwOXdoY/Xe0VBK4blwq9WfD/papgu8VaKleUFBbj5SngYRV4056T/pAsZORbVjatxzPBtzxUnSldajoQ==,iv:yThNbSpRU/xHPjT1xuWMKB5xd02C4tUJADHnzbK+wkk=,tag:qSOPZ6glAapvj76qndlgbA==,type:str]
    #ENC[AES256_GCM,data:i8qmB7qKGog7mdkBg0XkYffPftAZpYqB4g==,iv:6SxkIUC2xM9/TMQXPx42P12H5jSnhyEHIF2JbI1YTUY=,tag:UxsrqZjFBI3YERi4aWDGEQ==,type:comment]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:eDDUtl+Z8jI2odwIfJMzZEGkQ+i4Gq05yg1QPiziiFVCsLQrrAoZ3Eo/vIAcJOMRPKazRKVfrlx4ag==,iv:+jJk4q1NCfotqsLM/Szh8wEO2ozFa+utmTqKyBm7w2k=,tag:GyHC8nQTOryXcj6ZW/a3kA==,type:str]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:Y7I/GlqwFLypcCfP/xRGues0LvjXS2qPpDI+A0/heycE8n6/GTs2kKzOEKJTkbz9f2sK0CSz/vDqDcELorKD35gTkhFZwkviJ9U33JRmiH6y9bDIWP1rjEQ5xA4rNjCaFsQ=,iv:sRpN9SZK6gwXI/xr47qKJzrBN+3cWpmBwH8P4u2N5Ec=,tag:S5y55GNb92b3mTyUdEH2nQ==,type:str]
sops:
    lastmodified: "2026-03-21T07:04:09Z"
    mac: ENC[AES256_GCM,data:iWPWmowWK7t6ZAjCoZTvqJVaT43vMeJt7tjpvsBsH0HqzPusysMoTSTEM2Lfhjz0Q0dR0VUzLgCARohT3JfEbxJ1JIk/c1Dk9GKPn8WU7gbFEt2RLKrPyBmanzAgZyx8c31tlfU2sEd+WrwMoCvmNdaBlIhamCdOIX/RllK3Rbc=,iv:XREPoXgZcIOWJWm4ZBvY7OLvDi8eDEgBXZYADaMJy8s=,tag:Jy1s1N/P2JRJ6HPju4CHMw==,type:str]
    pgp:
        - created_at: "2026-03-21T07:04:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAcqU1cm+KVJFKik3wyglcn8IjEderRJyzIAeSp3aIyyUw
            a9UBl02DuKVHWQovqRQG1mHYpKpxquTQO1+i+dUqNcsDT0KFG1rGE6/uAE+62AHu
            1GgBCQIQpT374aH9Hgjm8rzWSbvcb+aDM7ffKeTgfmpErHjiypydEWJKNWQ1gLpN
            ShYhwrrLTy1lv5v5FE6hE4MM/orB3CfUXdw6bRCe9FQZiPtelhKTlL6mcNiJjLOb
            NEyqrBxSRXjdGw==
            =QIvf
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
