---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: github-runners-cache-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: github-runners-cache-nfs
  nfs:
    server: 10.10.20.20
    path: /mnt/fast/github-runners/cache
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-runners-cache
  namespace: github-runners
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: github-runners-cache-nfs
  resources:
    requests:
      storage: 100Gi
