---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: github-runners-cmip6-nfs
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: github-runners-cmip6-nfs
  nfs:
    server: 10.10.20.20
    path: /mnt/tank/climate-ref/cmip6
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-runners-cmip6
  namespace: github-runners
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: github-runners-cmip6-nfs
  resources:
    requests:
      storage: 5Ti
