---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  parentRefs:
    - name: home-gateway
      namespace: cilium-gateway
      sectionName: https
  hostnames:
    - prowlarr.home.lewelly.com
  rules:
    - backendRefs:
        - name: prowlarr
          port: 9696
