apiVersion: v1
kind: Secret
metadata:
    name: careers-vic-secret
    namespace: careers-vic
type: Opaque
stringData:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:35av6vYkpl9z4Wrnn7FXdGNR7pilpmWZifKe0/KWgXuZQX1Ibj62rUuMYTkD2Khyor8AxS1d6J5nbbBwIW5ZFmdp2wcTs3NvcbzvXB1x1tnYwcVPMFQ8ANNOYAQMOykLG+nOzzNZuCnFDcSw,iv:QOZUPbVwcXs6Z2njojCeh+XwgaiZqLsJ4yap3SVNN+4=,tag:EKEjsefJVpeKpxIzo0vZkg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T22:46:37Z"
    mac: ENC[AES256_GCM,data:wI2Krw2sKJJItHUA+l3GJpeduhNgz5ioRBneHZ3XN9GIAwxwbDEtGx6u5ibOUvWG4jSTrdWzuV10wITKP2EsBaVe4urV982HyiOe42jLwPhyjCMnXm/OqxcmTRtF8kCg5hvACXe3JTWuAmU2OQcuF3zVAOAU47967ox3Pjskqs4=,iv:12l9F4qQ57aQ85g5zdHUQkNLyY/k73z1qOg22VYOofo=,tag:fCFEXlvl2msPNVS8YuvIpg==,type:str]
    pgp:
        - created_at: "2026-10-08T22:46:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA9SICCDOiita/RZfKGGUU5n7pxQYIQ7Zdklfo/xAr9gAw
            WPDhm5+VwLqeX5kh/tVn8AYu9T8pKn8t3t2zAFS+ly70z/E3wzCYRy4RD4vWhYdt
            1GgBCQIQB1/GBpzKGY3GYwERtLmS/JIvWuXDSh89spYuZaUGuPClWZ8iVeOoJxB5
            COAwNAhSDIsCyvcS+3ArRa2WR/FTg62y5e6liztq7Dy3dgpyTxX6JaLH3DsKuSzp
            nLG0Pu8yUe92kQ==
            =2y8H
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.3
