apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: careers-vic
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:dceNDGQbKVDAJ5EBxKTIuNFUjoSjIHMvzzJ9CrjSfq0+X47fpi813OcGLfSJRf0G4mzctMZTU4UxJ8cs2XRMJNKTYkGVY0BaVtdOiPE1sMnJAn1UA3XAnYBw3SfGe8xa6K3f4jz4lMZjOYFRlZ/Ry5vinM6LQmO0aZbZn0WOBTEuAvMGUSJesw==,iv:tR7e/wmm0iLl3KX3dgWw3YRpaIVhqWRcOyBWAtYNX60=,tag:dDYwp14ii9opUsDX2eaCiQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T22:39:14Z"
    mac: ENC[AES256_GCM,data:ybD1ClGddNqrWULLNZ9cCpLgIDd/3ejwc2vgwyhRIxRMKzHybv1s5+KyBpPfXCRs8TNFvRA/Uglhg58T276A0agC9cYe8f3kf7c1bqrZgtqKjXU1ZvRMpQoVCD+tpGG6xGPq07KITKC5jwgLZjRFd44Jcx/suvPDvlekjQNFFkU=,iv:fgQ/S9ULS0uvUOVnzjUltiBw34LSHSvRLbeBzNdUsM0=,tag:Z+HSeb55qRO09R+sivSP4Q==,type:str]
    pgp:
        - created_at: "2026-10-08T22:39:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA9Ydxrck9VOd/xy5u9+znoREp9XQQADcAgNDnvBTs1icw
            9bM9+KT++u8STe5ztOW/d/PD89XU8/eOIup3G15kNtmGON0JEPj2s+BSGK/fXn5c
            1GgBCQIQ/bH7NyXCVH17HZ66pARiSrMpPDpEPOxx8jH3pzD4lviigulyxlUincLK
            Kpmu1rNYv7bl3tLrqxNVr+ZtgsjnD+KOpAtU10DaCBJwDQs1wLf5MjO/8pHcICX7
            XJzeKTRCYcPpXQ==
            =LMAL
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.3
