---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: careers-vic
  namespace: flux-system
spec:
  interval: 30m
  path: ./apps/production/apps/careers-vic
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: core
    - name: security
  components:
    - ../../../../components/alerts
  postBuild:
    substitute:
      APP: careers-vic
