---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: careers-vic
resources:
  - namespace.yaml
  - careers-vic-secret.sops.yaml
  - middleware.yaml
  - helmrelease.yaml
  - httproute.yaml
