---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 3000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      main:
        strategy: Recreate
        containers:
          gluetun:
            image:
              repository: qmcgaw/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            env:
              TZ: Australia/Melbourne
              VPN_SERVICE_PROVIDER: nordvpn
              VPN_TYPE: wireguard
              SERVER_COUNTRIES: Australia
              FIREWALL_INPUT_PORTS: "8112"
              FIREWALL_OUTBOUND_SUBNETS: 10.0.0.0/8
              UPDATER_PERIOD: 24h
            envFrom:
              - secretRef:
                  name: deluge-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8112
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
          main:
            dependsOn: gluetun
            image:
              repository: ghcr.io/linuxserver/deluge
              tag: 2.2.0@sha256:8e0d495f10f2ee29919f229ae0b32d92f2b7a5d5339fc6f171f19f3f94b9ed56
            env:
              TZ: Australia/Melbourne
              PUID: "3000"
              PGID: "3000"
              DELUGE_LOGLEVEL: error
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: 8112

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
      data:
        existingClaim: media-library
        globalMounts:
          - path: /data
      gluetun-data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 100Mi
        advancedMounts:
          main:
            gluetun:
              - path: /gluetun
