apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: deluge-config
  namespace: media
spec:
  sourcePVC: deluge-config
  trigger:
    schedule: "0 16 * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 3000
      runAsGroup: 3000
      fsGroup: 3000
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/backups/k8s
            server: 10.10.20.20
    parallelism: 2
    repository: volsync-secret
    retain:
      daily: 7
    storageClassName: rook-ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
