---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: deluge
  namespace: media
spec:
  parentRefs:
    - name: internal-gateway
      namespace: network
      sectionName: https
  hostnames:
    - deluge.home.lewelly.com
  rules:
    - backendRefs:
        - name: deluge-main
          port: 8112
