---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 24h
  url: https://charts.authelia.com

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 30m
  chart:
    spec:
      chart: authelia
      version: ">=0.9.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    recreate: true
    cleanupOnFail: true
  values:
    # Use Deployment (SQLite + RWO storage only works on single node)
    pod:
      kind: Deployment
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      extraVolumes:
        - name: users-database
          secret:
            secretName: authelia-users-database
            items:
              - key: users_database.yml
                path: users_database.yml
      extraVolumeMounts:
        - name: users-database
          mountPath: /config/users_database.yml
          subPath: users_database.yml
          readOnly: true

    # Ingress disabled - using Gateway API HTTPRoute
    ingress:
      enabled: false

    # Authelia configuration
    configMap:
      theme: dark
      default_2fa_method: totp

      # Enable Prometheus metrics
      telemetry:
        metrics:
          enabled: true
          port: 9959
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack

      log:
        level: info
        format: text

      authentication_backend:
        password_reset:
          disable: false
        file:
          enabled: true
          path: /config/users_database.yml
          search:
            email: false
            case_insensitive: false
          watch: false

      session:
        cookies:
          - domain: home.lewelly.com
            subdomain: auth
            authelia_url: https://auth.home.lewelly.com
            name: authelia_session
            same_site: lax
            expiration: 6h
            remember_me: 1M

      storage:
        local:
          enabled: true
          path: /config/db.sqlite3

      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt

      # Access control
      # ForwardAuth is enforced at gateway level via Traefik middleware
      # These rules define the auth policy when ForwardAuth calls Authelia
      access_control:
        default_policy: deny
        rules:
          # Auth portal - bypass (Traefik doesn't add auth filter to this route)
          - domain: auth.home.lewelly.com
            policy: bypass

          # All protected apps - one_factor required
          - domain: "*.home.lewelly.com"
            policy: one_factor

      # OIDC Provider Configuration
      identity_providers:
        oidc:
          enabled: true
          jwks:
            - key_id: "main"
              algorithm: "RS256"
              use: "sig"
              key:
                path: "/secrets/authelia-secrets/identity_providers.oidc.jwks.RS256.key"
          claims_policies:
            grafana:
              id_token: ["email", "name", "groups", "preferred_username"]
          clients:
            # Headlamp OIDC Client
            - client_id: headlamp
              client_name: Headlamp Kubernetes Dashboard
              client_secret: "$pbkdf2-sha512$310000$j1BmlOwgn.U.jLoCVe.1aQ$vgdSMEB37OSq1w58zQC9IeCc/DC0TTjqfteWfgiklXiWWRKTfoPXkU/vGPJyk3r5GEWw7Jx.agdPX2yrvkOsNQ"
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://headlamp.home.lewelly.com/oidc-callback
                - https://headlamp.home.lewelly.com/
              scopes:
                - openid
                - profile
                - email
                - groups
              grant_types:
                - authorization_code
              response_types:
                - code
              response_modes:
                - form_post
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic

            # Grafana OIDC Client
            - client_id: grafana
              client_name: Grafana
              client_secret: "$pbkdf2-sha512$310000$VekURqf0ljXCjHjMddpYvQ$Rn64VnakGxo2DiXDofbLrMRianuKKbi7wlz9CzcQvapqNuultRE9QpvM7b5Kv3tOMLJM91uYGHovZwB/.UmtcA"
              claims_policy: "grafana"
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://grafana.home.lewelly.com/login/generic_oauth
              scopes:
                - openid
                - profile
                - email
                - groups
              grant_types:
                - authorization_code
              response_types:
                - code
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic

            # Jellyseerr OIDC Client
            - client_id: jellyseerr
              client_name: Jellyseerr
              client_secret: "$pbkdf2-sha512$310000$21WDSLdCdMMkQIi2tP/I.w$YrqV6sdkWdf/NHmpZWlzzdfxBniAqZX8eeAZO4uWUPqaet75xtJtfS2vD/onJYWpwwGMuRFnMYaoWEOgsRuZFg"
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://jellyseerr.home.lewelly.com/api/v1/auth/oidc-callback
              scopes:
                - openid
                - profile
                - email
                - groups
              grant_types:
                - authorization_code
              response_types:
                - code
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic

            # Jellyfin OIDC Client (requires jellyfin-plugin-sso)
            - client_id: jellyfin
              client_name: Jellyfin
              client_secret: "$pbkdf2-sha512$310000$wubv7iMLRC2C4yWxUuhxRg$ya/T4Fj/m6oi88cpHdmQimqTglUzuEHrGm8YMZQjIIq9.kaOhr8WbAspUz5wPdsp0rgtYNvJxF08xQof/G1MIA"
              public: false
              authorization_policy: one_factor
              require_pkce: true
              pkce_challenge_method: S256
              redirect_uris:
                - https://jellyfin.home.lewelly.com/sso/OID/redirect/authelia
              scopes:
                - openid
                - profile
                - groups
              grant_types:
                - authorization_code
              response_types:
                - code
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post

    # Secret configuration
    secret:
      existingSecret: authelia-secrets
      additionalSecrets:
        authelia-secrets:
          secretName: authelia-secrets
          items:
            - key: identity_providers.oidc.jwks.RS256.key
              path: identity_providers.oidc.jwks.RS256.key

    # Persistence
    persistence:
      enabled: true
      storageClass: rook-ceph-block
      size: 1Gi
      accessModes:
        - ReadWriteOnce

    # Redis dependency (lightweight session store)
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
