apiVersion: v1
kind: Secret
metadata:
  name: authelia-users-database
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: ENC[AES256_GCM,data:Ip3QhlsPxad9exkQ8h1nQF28iP/jDf4drlyk4L+ab00sS56eXsOmfk+lghlIltjV2nDcDxpnSXJiy2gzuJm2FdNny/mQEIxxjX3hglVV55y6bIqanC9yRnd/64rlzw0ltGNqiFUsS8hNoddPVQ1T021Wh0CGWnzqC3fBLlFeh7sR/zErY73RLCuA9hyLQq4D6wPyGt2U+wAzUQW/Wsk/lLVHfpn3RFwXtPdjNhyuCAdZ83tAaBeVnCgv7IBnF4CaxtrvS1O0vHKY5+dvBPyrMyKNQ0/lZeoC6eRzd2yuzydEhkoaj5wH+1ZY4sMkojx1HxRSkuQChO1SeZq8TdV5KumE32BwnZ9NZ00fzx546hwBe7LONvzvhFBszEDkUVesnKgMwn9dFa/bOm8A//9Xm2L9a1T+n8EJ4uoT73QWE6bjyP8k0Y8fgzOM+LyfKOL8ZapabCSP1C37uQ+e3BHwneGAooqs21XsSb3BH9DQ0gz8XWXYCtosP7Gfhyn51yoi+RanIXmaYlHiATL8lagwJCaTNsPORCokfwcBnrh5Jy0D+LdFmLZ96d7HdeYAAPIdDNkT1TxOIFY+l4M2oduIIVcxi2irMG4acvco90UkC9d3gPbAwoXSiWKVVtIhuPyk3MHS1/HGIHq3sdqwSX+W5yKSPfKFRMM3i78XdEuSMMPM9rpgVDOsSLEn9mZZTHaAaeqQ/Bku0YaV7bS3r2i6go+XN3fwPv/SI3WeKkIv52cXoZ3jR4AgCDKXNZpVVmk7,iv:zRBKjlMKQa7lJu7vS8FfLOp4zoiOaQyK4gmzGPJxhgE=,tag:PmRVDhkM/xcPZAKWVcPVDA==,type:str]
sops:
  lastmodified: "2025-12-27T04:20:39Z"
  mac: ENC[AES256_GCM,data:4BpJGIOfZUPAv2HZ5enp3LwZwmrLF7uLAkyRxW8+Wq8BcjtvvOUGgzvhZ9pSxMpUM2eBky7THHWeDcJL7fvKtdu7NDEjY8SqMjksckohK7p2SoX3xDdBVWWWlnT0C11zYPJxmvmbef1dHtercyC7XDUpSvWPv5B1S+REqqRgfAk=,iv:kcarLidRM2HOzO+vRXgPTGYdViyRBPugIytEIHqMdiI=,tag:7NaVvMBNDwZij+x+cPS+lw==,type:str]
  pgp:
    - created_at: "2025-11-15T05:41:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdA+ymH7yJJ2HtWeOobO8DiC8hdsVA29vNK3gkwsC+4iUMw
        WX0XdqWPiWYYZ/tOHfYNb6Uq+ZYI2VjW/z6/TX8VE+m9VShem2eX4nIBiatPK2GC
        1GgBCQIQ6xvfP8nNi7O/Aw/DDp1PdSGhwr2tOE7dHyf+1uT8qYVC4xJLOU+gyZE5
        Rf733Xg0ISwF3Jvrqi2OsRWv2c2A1v222VLOUjlaWxi11AYmW3hBqcDFYM1irzrU
        a3Sv8WMeJoQwUA==
        =g+Z1
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
