apiVersion: v1
kind: Secret
metadata:
  name: authelia-users-database
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: ENC[AES256_GCM,data:+YsC7ow/kU2t8i9XSIuW32hsVgUbqaUtSsbn4H0TYxmOH0nyOySpKwUxcETSWsHRj6BGghelih8dGRcBH6u7WShfBccEgOoZpQtruG8oo3rIXEQu2AFL0gmbgg7YRONXpNkAlwny+RKVT0kLTzOUklm6ZX+230aL6AUiRlRgF4GGVTtnWe+fmYBzNCECVA/jgANxHhXZ0S40Ct5UJatVfYh7g4+UjMItDZ1hCN4pc7FJNvkrfbFfQVSYHLhPa2A9gPz4BGo8R+YpuoKSdbqAMMaKZUlrvMFgzyTMQKtBZdjPzoJNbrrQerGGL6nQq35mDghr/+XL5HeNu9pTowqPtBJG5vS1V3ejsLb5DOXTfgAG8WkKHi7lyg+O6NBkCDnQd6vbUhFRVBwe245+kUGP309imvCCwvf6ZMc4XAW9c3s+SGkzJFt6cUxpbrpZorWV/bDgNZouOLfexXSmZm/khqfVcGuP7Hh0xRwM33a+075YrcJ0JNoNaKdJKookbzHRHXgoOSNzwTLZtiXvZvhSt/yEQhhWxfWdKDCnY7BL3ed/chL3mxS4QRItCJUgjlJrO28KxwXfFRHoz+/4azCQDD7mAGQ1C6zdaP/1x98IilH58fjLa3J8uwP0tqf0ZeCrBiG7mBFgNkKc+dk=,iv:TtDk0G5/vIs454psZoBEe1Tjc2WkdxWPYl2bGbrhtao=,tag:C55FjroYI91mRwsU1H9TNg==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T07:13:58Z"
  mac: ENC[AES256_GCM,data:zrcdoPrFVf1eGNCoty2f0Cr16UC6BM7KDJntRd121JCHWbkmM7DGoBGQg6ZmUE65ULJFY76Hz4tN99nCcyPH9WfU0bW4upMr1YTkkRfjdIzqgRRVRkFHVwWk5QafLEF8LCrddzyr7A616h/jPMup0F1vnMEhC2t4IbgXtQOUSQA=,iv:LyQFv/Awr8mcuu+hi4HQg6gVomn66neTC4np1bUg8qY=,tag:t8XmjfnUSunu5bw1oage8w==,type:str]
  pgp:
    - created_at: "2026-07-11T07:13:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAbcx7MXiFCCq5tGcn3J44pkTagfICiEQ4/NFrR5PKwH0w
        SFN9nyJ20d6ttqBHpmvQKtQ3Lahh2WmTRJc8EbRN320Bx8kVF4juvJO4FSNLjzSl
        1GgBCQIQtiyqBGJ8IE2CDY+Z1ugLA7fOeFRXL/OeEX6qMxOjm3+Jyy2iwuajRmSj
        uN8KUrIS1uItEo9UseZXU24J9+Viu9+28/SH62yB1gtxfINo5lHl15zX1r9KdxxG
        awuWhUI1D4GzEQ==
        =T5ez
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  version: 3.13.2
