apiVersion: v1
kind: Secret
metadata:
  name: authelia-users-database
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: ENC[AES256_GCM,data:E2YtoRHDLQFMvwWEHlxi6dnQoHp2kg03ZeL1pNknYazxDpHQ2qva+lnpeSP+suFGEsh4VTOsqMlfLgPxDSgHwkge/vxteJ+nEmTSODizY6Go/gNpb2LgFVQyIH4SUj38w6h0aQH0zVDdzuCMIiZmbi8AgiUQEbprXxkobJdAlnsQ8IW7znu7LhblNSDL8hk1yuerinEfK0R6n8PM+RBVGzWVCM9dmNx0nlOPJ2L+COMpol2czMIIJsd3d+Hv4nDMlDZjW9FBLtEgaxYw0V7f3Py3WSowwe8/OMoxeJnuKm4z34KsmAwKOndVrht06bBc77i+vqOJpd/SeHcUiZBUyKSbkQQNI9P/CiknRZRdqU7pHmlH1vLZTJwZR241/s0JwlehsEg/OUVDGajbrVS+nMAQ5gK7jJ9ZYHjSwcGZ74fp+Khx9+BIFLKmhhsZCtXPgbMYx8R4jCkwmWuIJViUgUKS+m7u+OlGwV5fg2j3hBKz1c3YkvgXVoW4eXqQemgqmix34eHxJ8aPQjZwXnktI926PenoRjzydusaR2TjHN9Z37CUdaSEayrvFpRqSk508P/J5qhMkY6174eGhdLsgnXhoCC/BGFhFasP90frObSUwjtMgz7+LVFTVdl0EruFODW4N9jQGACuCuAr7Zl7By70qIlKeV0Q1PT3eeG6K4BvZw9CGXgO9Jei,iv:TNpyVeh1k4HpCOC95QWrSlxyZUeoTKWLGYJks1GfUmg=,tag:Qj+T7vXlWMZ8ulUploFbjw==,type:str]
sops:
  lastmodified: "2025-12-27T07:52:16Z"
  mac: ENC[AES256_GCM,data:WIcVhOJYwadLUwOrePkrvCXLVEX43OCK3JYHGMCgwq+ehf+OoRCC8t19IrFN2HDI6d24EZzw8QHIuHPZd+VpaPKl5CByHJwOPrUaMUwAGETEy7LAN2dgmpKzx6Xi68260QfTMAQP6YIdOHScCvvQSp+GutKGdI1ELNsHHwQ/gN8=,iv:M1vh4S+0E3gR3g7f3az3X4KSXoOE1GeImqJ3RoR66KU=,tag:VTG37J+cuaQORrWKreIo+Q==,type:str]
  pgp:
    - created_at: "2025-11-15T05:41:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdA+ymH7yJJ2HtWeOobO8DiC8hdsVA29vNK3gkwsC+4iUMw
        WX0XdqWPiWYYZ/tOHfYNb6Uq+ZYI2VjW/z6/TX8VE+m9VShem2eX4nIBiatPK2GC
        1GgBCQIQ6xvfP8nNi7O/Aw/DDp1PdSGhwr2tOE7dHyf+1uT8qYVC4xJLOU+gyZE5
        Rf733Xg0ISwF3Jvrqi2OsRWv2c2A1v222VLOUjlaWxi11AYmW3hBqcDFYM1irzrU
        a3Sv8WMeJoQwUA==
        =g+Z1
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
