apiVersion: v1
kind: Secret
metadata:
  name: volsync-secret
  namespace: authelia
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:mVkXsFG3FK6+GHVVg/a63u+dFLev1SqMo3Z9xFJUvTnyXeoK0zsuXMN1dQ4=,iv:KJzH0hAZ2eFPm9It6JoTyRHUnKkUj3wXSGVf35sS7qA=,tag:hireKLH2KUQoCZgkpjlGjw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:6oK8z+Ytyq2jBdAscamHeO/1wI76yd7T8hPkyw==,iv:HxuVp4oyu0SzrZs/0+lKbF25q6KeL/mkTJmy3Uvyxw8=,tag:U8LS43nySltaHZBo6bGmvQ==,type:str]
sops:
  lastmodified: "2026-04-05T23:51:23Z"
  mac: ENC[AES256_GCM,data:cs4EGvO3TqGSz0Ojo9VbTiCW3hTtixlIlDvPsjCttoWZPToGsZo2lCKw07mydrdPWhAAtDLBBcxS1SA0IaQXaA7aXhalB8i80/UgwJOZxHqLVdryxX6L0gXZJ7kl2lqk+S0DEyOkKuYveAH5qbuDkGIoTKUoeDXqtdq3sVkUzjs=,iv:dOB1erHi5mYu+X9am7Ak7PtEYJrjbAJBlZEZuvIL3M0=,tag:xSZqm/SLMPc+hMNHxhhauA==,type:str]
  pgp:
    - created_at: "2026-04-05T23:51:03Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAyQMyWOABkaiHODYvn05UZ3QLnjAbXW5RkpBpAAS04AYw
        gqBfJcKYGu5BGAPmtVqq4T/rkrajvMd5pLthshgvhBGP8blRYsA1IjrMcZ9YpYZy
        1GYBCQIQq0IqvDEvnC5dMu+YVFRR8rfeZ4M1bEa9Kmc0aFZRuyOOvwqX0VQ5lNoj
        hyWnJzqVYXq1XxqCeWuDQgjemhcBvvPgWrRSIh2y/kUZv/BpojRnmkCpVFfUoDGy
        45drm2nb/g4=
        =Nh+f
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
