---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-rocm-models
  namespace: ollama-rocm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 50Gi
