---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: climate-ref-state-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: climate-ref-state-nfs
  nfs:
    server: 10.10.20.20
    path: /mnt/fast/climate-ref
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - rsize=65536
    - wsize=65536
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: climate-ref-state
  namespace: climate-ref
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: climate-ref-state-nfs
  resources:
    requests:
      storage: 50Gi
