---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: climate-ref-data-climate-ref-dragonfly-0
  namespace: climate-ref
  labels:
    app.kubernetes.io/instance: climate-ref
    app.kubernetes.io/name: dragonfly
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
