---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: climate-ref
  namespace: climate-ref
spec:
  interval: 1h
  url: oci://ghcr.io/climate-ref/charts/ref
  ref:
    tag: 0.1.0_pr-492
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: climate-ref
  namespace: climate-ref
spec:
  releaseName: climate-ref
  interval: 30m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: climate-ref
    namespace: climate-ref
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    recreate: true
    cleanupOnFail: true
  values:
    # Global image configuration
    defaults:
      image:
        repository: ghcr.io/climate-ref/climate-ref
        tag: pr-492@sha256:f834a3c1dae4f3b9e68f05f3dfd457cd735911636dbe19eb64cfe97c525fa2ea
      serviceAccount:
        create: true
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      # Mount writable directories for app data and config
      volumes:
        - name: ref-data
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      volumeMounts:
        - name: ref-data
          mountPath: /ref
        - name: config
          mountPath: /home/app/.config
        - name: tmp
          mountPath: /tmp

    # Flower (Celery monitoring UI) configuration
    flower:
      enabled: true
      image:
        repository: mher/flower
        tag: "2.0.1@sha256:51c3c3db5be343e6335e3dbca5348708932bbcca992df6a39f1dad91e3b340df"
      replicaCount: 1
      service:
        type: ClusterIP
        port: 5555
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        capabilities:
          drop:
            - ALL

    # Dragonfly configuration (Celery broker and result backend)
    dragonfly:
      enabled: true
      storage:
        enabled: true
      extraArgs:
        - --proactor_threads=1
        - --maxmemory=256mb

    # Provider configurations
    providers:
      orchestrator: {}
      esmvaltool: {}
      pmp: {}
      ilamb: {}
