---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: binderhub
resources:
  - namespace.yaml
  - limitrange.yaml
  - helmrepository.yaml
  - resourcequota.yaml
  - helmrelease.yaml
