---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: binderhub
resources:
  - helmrepository.yaml
  - resourcequota.yaml
  - helmrelease.yaml
  - cloudflared-secret.sops.yaml
  - cloudflared.yaml
