apiVersion: v1
kind: Secret
metadata:
    name: binderhub-secrets
    namespace: binderhub
type: Opaque
stringData:
    PROXY_TOKEN: ENC[AES256_GCM,data:zen5dbJYdp3hyLwLlCkJFbBDilZUtkbCuYbMiWpE/8mRS/7TbRyilP1aTHmmDGYdHAZM1OcMOr1YzYsisyLTMQ==,iv:Vld27eA9d/rFOjG3AZkVRCls24KHeZdhGeSQzeukjRY=,tag:IXM7cDXFp73u9WalMf7Tow==,type:str]
    BINDER_HUB_TOKEN: ENC[AES256_GCM,data:zKxa6qdiiBHEiUzP/5LD8MH4YtM9Tlz+FmkySrjxUZIFl3/8TxtAZ4Bs1WOUV1npgf/RcJu0w0Ef8hl3QC+65g==,iv:AiGYO75KBM18kpQIpYdP23etkZHNbqySa5yuUUIGI/E=,tag:W0QwjehmsAUrZJNq4qez2g==,type:str]
sops:
    lastmodified: "2026-05-27T02:59:43Z"
    mac: ENC[AES256_GCM,data:+kP9/uLqimeGVGhpTaLUnnwBqGtFsHxbtMxgC/xLkRzQyBTjBBIIgvN9hq7DmfvHMMvH1XqM6SEErA0IiQD7we+JqkMmz2d8OGapjU/m4DXyUpz15nOkQ3O7ByBicdiGI3hb4jq0jRnawJPShqN1rVfFHV1wAzYRuA05isMKpek=,iv:EUj5l4syTu5iYnERv0AT0bbKWDpqBZbaqm82/0Pm7AU=,tag:Q3hiQnwuPud6JmvTQqHPog==,type:str]
    pgp:
        - created_at: "2026-05-27T02:59:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA+1UQojNcV36aWY44Xq13FckRBeLTGF2rXaklfIxTmXYw
            qXhmGMtE/+zCMXoioBIUqsVO1IG0t7RpBMLQ00pBJ8LYAvc9OWGSigkt3MO/kw2T
            1GYBCQIQFwlLZuqZ7FlMzZgkV9hngFjYGc5yCIaVruSyfRzKpL9Cv58xm9v5m5Nz
            UB3bmQU5G6g67a5nSIOaCn/mkmv0ogrkuJx4pNg9XCx82CQKQA1WjYo9S913+xI/
            fzsg/q8fG94=
            =HXC/
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
