apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-issuers
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/base/cert-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
