apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-clusters
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/production/database/clusters
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: database
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
