---
# Deploy Grafana Operator first (creates CRDs)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  retryInterval: 2m0s
  path: ./apps/production/monitoring/grafana/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grafana-operator
      namespace: monitoring
