---
# Deploy Grafana instance and resources (after operator/CRDs are ready)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  retryInterval: 2m0s
  path: ./apps/production/monitoring/grafana/instance
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: grafana-operator
    - name: monitoring
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
