apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hubble-ui
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/base/hubble-ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium-gateway
