apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/production/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core
    - name: storage
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-operator
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-prometheus-prometheus
      namespace: monitoring
