---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: technitium-rbac
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/technitium-rbac
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
