apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: date-jar
resources:
  - helmrelease.yaml
  - middleware.yaml
  - httproute.yaml
  - httproute-api.yaml
  - networkpolicy.yaml
