apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pajikos
  namespace: home-assistant
spec:
  interval: 5m
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: home-assistant
  values:
    replicaCount: 1
    configuration:
      enabled: true
      trusted_proxies:
        - 10.42.0.0/16
    ingress:
      enabled: false
    service:
      type: ClusterIP
      port: 8123

    persistence:
      enabled: true
      storageClass: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    extraEnv:
      - name: TZ
        value: Australia/Melbourne

    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: false
