---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: climate-ref
resources:
  - rbac.yaml
  - cronjob-weekly-reset.yaml
  - cronjob-ingest-solve.yaml
configMapGenerator:
  - name: ref-job-scripts
    files:
      - run-weekly-reset.sh
      - run-ingest-solve.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
