apiVersion: v1
kind: Secret
metadata:
    name: slack-webhook
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:KK/zT3KWebc/ZlYVwHzcNXMxpuI9kTJbjzF8XgZWT4VhNnONxgo/0Q8YgH3jEZ36Rp4FHMhDCnQjqV0A1/yFuS0Cr7GsUYSUO8e8Ifhk6cYg,iv:ypDKVUt5mLii+Q090g233TYl6fqG9gQYjdMdvYZZdgw=,tag:4yhUVO5U0giHN+9LGvor5g==,type:str]
sops:
    lastmodified: "2026-04-14T22:49:03Z"
    mac: ENC[AES256_GCM,data:e4qD21gcHoAer+YhvVmOeKQvBvSAH5SGDeBE0h+JVDhJa+jK/LtTzEtPEQpmGPMgZts2n+531f8sDHkkW8gZUcfELjFJIJwg+L377eCb8xavXyCe9W2SrTCX4JstftahI7Jc0uWjPaGTlelO4pff5Y65SbwnxmjgrlrcZYYMdwY=,iv:k7wT29FtY1d3tsXcsrIJgYs8GQWYry0i0e65z7WGajU=,tag:tDjfYPt4vBtq8Oai4JwQfw==,type:str]
    pgp:
        - created_at: "2026-04-14T22:49:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAmVYjbu8YJALKZqyaJv6dQytzjt0frkYzyNLbIvQRIhIw
            WdlK+ctKWvgQV+r1g6VDbJEi9IiQPUiIue0ld8FtIQUFSWf+NgyDSaCjESC1C8uK
            1GgBCQIQwZyeJrTHgNTVzaILp70Qo446NlBLARQR2T1wmBB16D5mTZwa3DmzqdCe
            iz4aQ61BYFGLI1oC2tRgM9QHxk7JpZ4tvBaTu6chiwyXuKMedOSpGTc9wDaP3ce/
            rJHUJk+kBF74qg==
            =Ullc
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
