apiVersion: v1
kind: Secret
metadata:
    name: vela-preview-github-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:kQfz4hRYFYviDI/yEhhX51Cj+S8UjLLd8Yp17N882b4E9/kvH36k,iv:S7WAH495r/nDOp69RoASJog/wrIb5r7eqsYiT3x+Udw=,tag:6FR97RzfhIlClfGbh50epw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T04:38:38Z"
    mac: ENC[AES256_GCM,data:4j9suA62VQsUESwo5nUZXRTrqxvoqqUeGGVWYlmxgt6UDL3wLhYoDm1Dc9X3/P5Mjfxes56+9S9/c8zRBs30FW6as6+WfSbSN+HkThJncI5rjmgxGh14HYf52yehf+EbH/z7VPRVQJcGmCxYBzuDfWGkNqoKuYa5GMCby+DIRPI=,iv:PlGjTQx+RXAfFN4Y0PViKoj2yKmluqk+/LQvSoUxQfE=,tag:kG4Muh7AYzid7gbyWBO7PA==,type:str]
    pgp:
        - created_at: "2026-07-02T04:38:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAaXdI86FNT+5j1TEi6CnGs+S6Igd3iTEOTzMRZnKwZ24w
            JInlor7HNOAdE5/NdTM4y5FWnrFIHSkdv5uLJ1gU1c7wHFQNG/cx6Z3xY/TiaiG5
            1GYBCQIQ/43lr0HjgiqK32PF0MOJ/IvKNjoQ3FxhR1CPJ7ijosnFxmWWu4eIu/fr
            0/BkEeKCZd4jFVHpqiVTfvitoBch2I53GmCu9D3mlBALuheyCwatXdBHIzXXPVkM
            elvHRHYJ2Hg=
            =uKCt
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
