apiVersion: v1
kind: Secret
metadata:
    name: vela-preview-github-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:lCLp9TP6Q9KliBUjLX4tsy7E3+mA99cbI2nz/nlbb09CIDq/aBQ/9ZPTSJloMH0/6aAEm7l3D56wTJm+bp+QQMoLcNJ/WcdUQwsE2XES9PpQOcnbK+VOyRAY12De,iv:NpxaI3W9Ncu1fkNVtQpT3aEmbNBbDV6ZzN0J/Hllpvk=,tag:/Lz2KenzWF5CsYfha2Azpw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T03:16:45Z"
    mac: ENC[AES256_GCM,data:QOm3zfcQjhRKKecS1yPwLdh8lsFercHdj344nEKXxSX79Tz3qISy7izY74X+Ut80hm3znXfPVH9ZxRyqlE+akxCVXuofw5dnda6bK1M3dL/P5M+B0wU1pAnuBWlv/DaIMF3EXBYiUfvxz+1W/dFgknoaj+8Kx51LWvhnv7ubqcg=,iv:cCW+pltgwCzDNqiwsbF8MDzgsmMIlWDBV0ASTiqkpQU=,tag:G+v5V43kAoYoHiUSBafxUQ==,type:str]
    pgp:
        - created_at: "2026-07-02T04:38:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAaXdI86FNT+5j1TEi6CnGs+S6Igd3iTEOTzMRZnKwZ24w
            JInlor7HNOAdE5/NdTM4y5FWnrFIHSkdv5uLJ1gU1c7wHFQNG/cx6Z3xY/TiaiG5
            1GYBCQIQ/43lr0HjgiqK32PF0MOJ/IvKNjoQ3FxhR1CPJ7ijosnFxmWWu4eIu/fr
            0/BkEeKCZd4jFVHpqiVTfvitoBch2I53GmCu9D3mlBALuheyCwatXdBHIzXXPVkM
            elvHRHYJ2Hg=
            =uKCt
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.2
