apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: vela-preview-github
  namespace: flux-system
spec:
  type: github
  address: https://github.com/lewisjared/vela
  secretRef:
    name: vela-preview-github-token
