apiVersion: v1
kind: Secret
metadata:
    name: vela-preview-webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:WoZn2ftFS/tTZQ7aNtnAPaSngowBB2/iBOCGcfhz35bDFdlw7y4kRq3zMA==,iv:/0zyANef1Wjd2crDZHgPeAiAGbJVrwR/a1BH6UEOYOE=,tag:iJBof1VXkmQZ9TwffMX0aQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T04:38:38Z"
    mac: ENC[AES256_GCM,data:qPy+mOXtgE3UtPVezM+yPC8SqZuatYSBx2OGIlbYdBftGM0kATqs1uC9Dzt/p5myPs7h1iZL2Gw22NxEoqJBy47Z8Sz7bJQtlNKeopYpp/DX4wTwvk1Ym2Sbfm10jijwNJQObITxg8dNGYtfhPEGeQdwyC/RoZ348c9fvaFOGqQ=,iv:pdxjVTs4Cs3CanlnZ/Rec5zG0gNrup5pQGHegWEBgJU=,tag:opQNUYAZ60fT3ciFYH/PiQ==,type:str]
    pgp:
        - created_at: "2026-07-02T04:38:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA5zinhasXAyrn4xONLwawe6gBFrurc0GoRBddxIaaOVIw
            0jLOAE0OaEV7s8FXTPKX8yYvGItYQacPldicfzRecHucGyNze4Fq+rPFUXqYOZWk
            1GgBCQIQJq8EMW1Fj3t0zKRZ4eXUEPxMANh5E9rlHbmiMYmHofiQBD9oogIRt2qH
            gCOTKeTA+FMS902/82K1vGn+Vkgn8yJ7jaoQoKwLKlhJLN44BOuuMaCLWHch93jR
            SbHR37RLgKS7RQ==
            =fHoO
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
