apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "0.17.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 1m
  values:
    provider: pihole
    domainFilters:
    - home.lewelly.com
    extraArgs:
    - --source=service
    - --source=ingress
    # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
    # You don't need to set this flag, but if you leave it unset, you will receive warning
    # logs when ExternalDNS attempts to create TXT records.
    - --registry=noop
    # IMPORTANT: If you have records that you manage manually in Pi-hole, set
    # the policy to upsert-only so they do not get deleted.
    - --policy=upsert-only
    # Switch to pihole V6 API
    - --pihole-api-version=6
    - --pihole-server=http://10.16.0.21
