---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-actions-cache
  namespace: github-runners
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi-fast
  resources:
    requests:
      storage: 100Gi
