---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openviking
  namespace: flux-system
spec:
  interval: 30m
  path: ./apps/production/apps/openviking
  prune: true
  wait: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core
    - name: storage
    - name: security
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  components:
    - ../../../../components/alerts
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: openviking
      VOLSYNC_CLAIM: openviking-data
