apiVersion: v1
kind: Secret
metadata:
    name: openviking-secret
    namespace: openviking
type: Opaque
stringData:
    OPENVIKING_ROOT_API_KEY: ENC[AES256_GCM,data:rCQV7HSDvMUAMHkd//CpgjZGi3D8CoLcAUTxM3uI8LNptuhIOA8Yx0WBIiMxF5aSc9riqgKZkiAiC43Dg0itKw==,iv:wGAI5CEs2/cW+N0s+Opo8Gfrwbn+unLNFzZSh478VaU=,tag:VJ6SjF5JUJc63/OK5+bWbQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T01:58:48Z"
    mac: ENC[AES256_GCM,data:RhvwAdhHpYQErEQ+/Rpeyuf3VJiy6DfCvlyp1p/0Xmpgt3KGK6X2Gu0IUHUIa585ovfDEXe8V5e4IOuMvMHsHvGtuPkI1S2HcXsx0W1r26/sdXsw4Md2oeIjGFPwg1teWxB4ruuRwiW2lSNUK/nNRIFZyUFWHDiG4A6hrziwzmw=,iv:dTq7jid8Ukh0d8haCbbRwPepxPd+a2KAvTFoig2//KY=,tag:ivt5q2d0tdl71/YbS5p6qw==,type:str]
    pgp:
        - created_at: "2026-06-30T01:55:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA25qJa5Ys4w3sGX0s838eAyKG5kI0csUAkmXi+8xWjT4w
            X7mYb0Lqs5mok5gJFOjWuY5bgbQdnWHg+Efcmul8MEKapARSo99J8K6A0N6pqIme
            1GYBCQIQfJED7TUzz1yLX2+GaRSBKhzc0NMF9XfY0XczZAFMxrbQuMyJkmlxM72+
            5/6mnFuJ9HbQcNw3DL+ucX77swyQtDlaYdHd4mIBr4GQm9uRx5hOIobdK5+NNlx2
            5qOnJWkr410=
            =JUyL
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
