apiVersion: v1
kind: Secret
metadata:
    name: volsync-secret
    namespace: openviking
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:/T2O/kHjfXJ5bHSj/s4qUU/mjWNIRsnMLzlYMg==,iv:RDzrEWJtOv5+BS5iv65axhqkhCTC1H94dL2I8dlQ1n8=,tag:UOzzFUIguRK96R/l6JkofQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:pDKBrMVoAISrQ0Tyi1VJojJ0KrIrn3EYZ2oFIG84t8wV0y1dXkwUJM6qwUo=,iv:nBfSJIEpTdvnduq+xIrJ34FxVBJafRW/JEXyIkE522I=,tag:2lfLNp6TpKfJrzRdaJgBvQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T02:32:48Z"
    mac: ENC[AES256_GCM,data:VyYRq4GJE9pk01YXFUN0edcuXZFL5wrz9V9A94sirsUGVu7J5KQt+2tTP7OTAm0MUThfpNVmRbcjYGda+25mGyUwmE5AJafeA17YlH98SdiHQPY/shXgnsH1G24RiUUEzoITjIaBekgrNqYlylEhLFLlfrU1bLiihvUI/97tfdw=,iv:tatSK0MBjS3edvw7B5bLgpQlfHuBEPUxYtNBKZg1hfo=,tag:Ab34Jv5tuSheigUeVqD4DA==,type:str]
    pgp:
        - created_at: "2026-06-30T02:32:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdASh37qDU/mmlzjzdaSHiafCCO68TLOFH47MnH1azz3g0w
            A1yhAM82QjM5ioTGlH6vc570ZHk052htoMAIfzfvsthWFYjkG/lcZaZ8rhak3AVl
            1GYBCQIQ4Ko3UPPm6vzL1uRInRnz4CQT49bosQ1MkmoieEM4JdJZqwfB8iUJQTRa
            DS7TFVBnAAm6dHiXe66L1Me+OdG+VM8wlDMVL47hU+78crDVWgSsdQaouA8Cml5B
            GKbMCanOWcI=
            =o7UM
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
