apiVersion: v1
kind: Secret
metadata:
  name: date-jar-migrator-password
  namespace: database
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:DjjDZd+2IesSIeQFI0DIYd8=,iv:Us68c2vNf5B6bUvN0e/cL8joblfAkMwDr7tULD7m/zY=,tag:J0FNpTe8hYS5EjSoGAi/sw==,type:str]
  password: ENC[AES256_GCM,data:p8PinvKgbH2QAqAiU6vIghRUnbguOXwJkVYOA1d/aHbmRrObK/KhuADhbieuWm5luz4QKyxfBJFMVh7Ql0p0Eg==,iv:ykGbnxeVd+/AZd0/qUSynX0UYFNQcIxZTDuMWSGykkM=,tag:BE2tYpvAkEhUI+o7ejBvig==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T07:13:57Z"
  mac: ENC[AES256_GCM,data:FM9JCPHkXDxA2uOqANMKUWqbOPTBQD8c6budCHYGX+bZChkAAmf+bu3WCSNTXCKQNkuvy1uvreVFwPDtitDydrTy0CBj9l+Sp83sD2oRV+2gWbf7Vw5g0xur+Az9ujs+5wENaAzSjAfMNF8OKiI9+07lt5oKzR1J/HjK6Cw/oCE=,iv:JXLyVHijYfLwMQkfugQ1C1QppzIIHLso8CnV4xdfYVM=,tag:3oxK3ahh6GtMNlv0l2Y9OA==,type:str]
  pgp:
    - created_at: "2026-07-11T07:13:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAEr8tfdGO8Afa4uxLMSBgig4xO85Epl96yxZfGzF+9Ckw
        +A8AGuiJ5HxFjajnbysbI74Y9ape5+AinU30cqc+/uribjs1HAw7EyNL0adLiNRG
        1GgBCQIQQlRN74DRxdK36OvbLp0q8ov5kJT0brZyWCu4zZSjQaMhrfwY63cNV9cY
        aQ/uJssfb9jYpddKbMXTL76bwiK/joOeAbGpkzXJaAxqWqrywL+UwCsvfLlA8Wcm
        fIM77stQjX6qqw==
        =KlWZ
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  version: 3.13.2
