apiVersion: v1
kind: Secret
metadata:
  name: date-jar-app-password
  namespace: database
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:XAMW8UZgeMBfJ8aI,iv:+2/BkGrz751ioKYRNuv39lmmCfgOscHSDObnMITKYwM=,tag:zMVge3n+0SUKUKHqYjKjWA==,type:str]
  password: ENC[AES256_GCM,data:O93BL+WWILtCC5b2W0rU+TfGYxP37aLb+YxtUS4I87l7cmJQmCEYGJ3DyIMPexrdeN/7h39EDtFbKXLzwPdKoA==,iv:vWCk+IqhMoc0Qo84urYwBKwJZ1oIkf+TYfm6Fdr9kCY=,tag:k1t9WfHy24RpQ+2qnypIyQ==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T07:13:57Z"
  mac: ENC[AES256_GCM,data:s3ePSU3b9Rl7b0hUa5JSwbR35QDW9K/9O4dinvO+qoQMZLg1FYE+udDFsvIC5xNVik/B+m/XrdjMvL0euLlvmYxGaAAbFqfC3FN11wM24QbZMiqnNT47cinsIl3nCRHC7QDIK+gvw0R0JkKoERZJ1LXRsyi1TbyhqBFJZnQpjug=,iv:SgHJmPgnK1DklqnSop+4XZFAWRg335fMZK+Kv0dhA1k=,tag:Z3SP6yll/g8Kxl6YZ5m2qQ==,type:str]
  pgp:
    - created_at: "2026-07-11T07:13:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAam7irMSAEmKP73NqMnqq/7RcRQVIlvLmKjCJTz2ZH2Yw
        WFCUDEkhI8g/JHKutrtVKwvIzBbzjB6cLryCs79CPbuuA+MuyvXizJlqRFFyEfM7
        1GgBCQIQh3RriMrLLr1bZlwUXRpEV8IMpp/FSh3FJnDM+Ca6iYayaV4QiX9SHkG9
        yTZdScf78jZnUdCUB/YSrprhus2cd8EavfjiLE2ydINPWLJqPHjAXjlzGpKqQLxC
        thTbz3bZLagC1A==
        =ABgw
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  version: 3.13.2
