apiVersion: v1
kind: Secret
metadata:
  name: postgres-barman-s3-credentials
  namespace: database
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:XRVlgFXSg3jDfgzAJ0/iCN4PmIuiVDCgDonhn4niyCWOvGEUjx6oXA==,iv:RXStVuogiVfK+YqTGEjO5rXk7OZmUjXjHSqB64QLDJE=,tag:VSVcFdC+/3Oa/OVU7cuqEA==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YsHX5y7la6dvTz/JyVnjIrnwg3lfAe2qWSaSMdnHGspuBwraSuWMyeBfd3tevPFHteQpE6GosFSMW0hVfvF7hYbD0j7SWRxoxUcCV65Q/hM=,iv:zdVrCzgAEPTxm0Ze7PRy0FA8t2fpgcmBJpcszsYN0FI=,tag:4SU6pEvtts9f3Tl85MvPLw==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T08:55:28Z"
  mac: ENC[AES256_GCM,data:jECyaIYe/VpOW/SJhlUIVMHaaUNoznkZyV7FGJPQg+W314RBxQ6f2sh89i/2+ljQoSPLVDmzgHW+Yg07tgD7HGongFWHKL/hDI3aUOOvw/bfLJ4/W4Vyl7IGit6BCrFUiS/7wreSpuVtCCyzdBqqJN3ELRyt4ZGbLr0UEPQaavg=,iv:tnrxnyZZrNFMX5eM/Fp7sYB993dw/kjfTLMDeexsBkI=,tag:Gg9kB9QtRGFmqOTplwJcJQ==,type:str]
  pgp:
    - created_at: "2026-07-11T08:55:27Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAmqXlE5Szt18lSpIfof5t3MFVHI9jXju0BfpK1e9GY2Mw
        hJ2fFTunEFPg7VpKOXIL0JTbvhPzQKOoqQU14452kI3NRZMSJAlRlGG8WOgsDcBo
        1GYBCQIQ7MttwjWZ6emINrhUsZ7xSAxx4XydIHns/+FaqMHKKLdYLzikh7XczFj8
        Sio7lXOPNwD1ulObz/fSXLrlj5g0d4Q3RQgY28d0R6GpEI3lQO027+UNDQeLQwdA
        girS/6kctXA=
        =0Ds0
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  version: 3.13.2
