apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: "256MB"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 10Gi
    storageClass: rook-ceph-block

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: app
      owner: app
