apiVersion: v1
kind: Secret
metadata:
  name: postgres-barman-s3-credentials
  namespace: database
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:GvsGFWJg/C0hzfj7oMdi3h+Ze0MLdPXvHDok3IPDvXvspWkJ12NPkQ==,iv:YQ30svyU8LUE+M+RlXbC0Lg7CRHW8GadJ+5NA9PDqTU=,tag:oKemLqoIs5JZsrnWMIlrGQ==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2l7sHTNLIdnEV4B4Yw30yjsCsZd2ijpT/aD1EeNZDC8FC/20QrPotIdNS/rRp7Zs6XEfnUYCg6LfLhcbvZBt44KfzuSX+HZQsQMajJD9tEo=,iv:6G874E3kfnF3Q0jaAsMGCzfpOzzNuYypqQD0m9oBpH0=,tag:xgX/GBZP8PaWuXAMp6FeIA==,type:str]
  S3PROXY_IDENTITY: ENC[AES256_GCM,data:/TezNAFexaPStjj9gwvvRsSg/3E/F68A+pQpY4OOaIy7/BfFC2qCww==,iv:YWNn9qBHJKv8UxInkII+PqQMbvhblOL5NcB+ZXB4JY8=,tag:p4j8fC6w74lInTZOrnHRxQ==,type:str]
  S3PROXY_CREDENTIAL: ENC[AES256_GCM,data:g7cBTZRKjxCTZzAihQG+f1UE0hPmuZIZeKjAHrMSrwVicTQ29s+0T8VPf0MkcD0nluxOSjgh9VA9YCGDZX1S0bgramCA+hoRpCxqcaID0C0=,iv:T3yzbfgpddceWVAKpcIb5hwTMWBESwFCuwAVQusepsU=,tag:CVEcrteqxpN9y4AOs7IPzg==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T07:13:57Z"
  mac: ENC[AES256_GCM,data:i2gCMfi/zCFaa+fnyif/T88Y+/nkdvyNyNFtT8h1+kEc4srIw4BoT5rLVHMoYotL4bV/61rkM4eo9HkC7dIiIF0qhf05zaXEs+EjVEdNvXe2daVyxjq9dUDWIKNL84jdP2ogDJvccbanAq+Lw7PzzkihnwbbcfaTgBtRC0ohS4Q=,iv:bHbd3doVA6mMykuTpZRzGObUP1UMti78JDddUx2gf40=,tag:depad7H7SybZXMEP1/Gehg==,type:str]
  pgp:
    - created_at: "2026-07-11T07:13:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAhmAEd6TCNt3+4UEsIO+2ebnF1mqwiwQAtLR/Fyyn3k8w
        gvXCS33AMXthDZxOXPV1ZA+T0k90J5WsowBPyYkOGJ+ufE4yR9NeRpxxFDnO8MIc
        1GgBCQIQBs/Ipy6D5hVLcnVKz6Mphr6oz2DZ4+rQ5+toJGxJBXjjMQKFIXfpUmFA
        OV0pRuPHJwfyDKuFpU7PYXX+lahJXB2w3Rifa1v5FbeP5B5aKoUFIJGbTWVDGfT0
        Q+J4o7MVyXLHSw==
        =174n
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  version: 3.13.2
