apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-gateway/
  - cloudflared/
  - flux-notifications/
  - traefik/
  - external-dns/
  - flux-operator/
  - keda/
  - metrics-server/
  - pull-secrets/
  - technitium-rbac/
  - reloader/
  - tuppr/
  - volsync/
  - snapshot-controller/
  - spegel/
