---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sabnzbd
  namespace: media
spec:
  parentRefs:
    - name: home-gateway
      namespace: cilium-gateway
      sectionName: https
  hostnames:
    - sabnzbd.home.lewelly.com
  rules:
    - backendRefs:
        - name: sabnzbd
          port: 8080
