apiVersion: v1
kind: Secret
metadata:
    name: binderhub-secrets
    namespace: binderhub
type: Opaque
stringData:
    PROXY_TOKEN: ENC[AES256_GCM,data:zen5dbJYdp3hyLwLlCkJFbBDilZUtkbCuYbMiWpE/8mRS/7TbRyilP1aTHmmDGYdHAZM1OcMOr1YzYsisyLTMQ==,iv:Vld27eA9d/rFOjG3AZkVRCls24KHeZdhGeSQzeukjRY=,tag:IXM7cDXFp73u9WalMf7Tow==,type:str]
sops:
    lastmodified: "2026-05-29T02:56:56Z"
    mac: ENC[AES256_GCM,data:cusFRZclHv0G0zY8BQBMicRQP+MnCgsfO5pwOYG02dZzE/BgFwaqj2rBYMCzqUGPIwAQ8MAUPnXrbqWzH9REGCMqUaaLmYnKZBSFFmyaSYPQigeEwuSzWs8nrQ2VMt33nhZi7Y06dK5Zjz41WYUPQBLm5QIR+UfTYFdxfKZ0RZA=,iv:aKq8BUrUwiN6llUTy0BCAkpyuKx5WYB7FdVhFSfizMI=,tag:Cyaaun5fovCKb/U/yRuPoQ==,type:str]
    pgp:
        - created_at: "2026-05-27T02:59:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdA+1UQojNcV36aWY44Xq13FckRBeLTGF2rXaklfIxTmXYw
            qXhmGMtE/+zCMXoioBIUqsVO1IG0t7RpBMLQ00pBJ8LYAvc9OWGSigkt3MO/kw2T
            1GYBCQIQFwlLZuqZ7FlMzZgkV9hngFjYGc5yCIaVruSyfRzKpL9Cv58xm9v5m5Nz
            UB3bmQU5G6g67a5nSIOaCn/mkmv0ogrkuJx4pNg9XCx82CQKQA1WjYo9S913+xI/
            fzsg/q8fG94=
            =HXC/
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
