---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keda
  namespace: keda
spec:
  interval: 24h
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 30m
  chart:
    spec:
      chart: keda
      version: ">=2.16.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    resources:
      operator:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
      metricServer:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 128Mi

    prometheus:
      operator:
        enabled: true
      metricServer:
        enabled: true
