apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pat-secret
    namespace: github-runners
type: Opaque
stringData:
    ghcr_pull_user: ENC[AES256_GCM,data:QctA9EgHDhuxcZb9A2MVYUCOFbGBXslRTDS2o0yrjCM=,iv:RtbqY4ffzBPkKP33Q8JGLLnfHKB7Xq/RQs8gCx/Oiq0=,tag:MVK0RwtWmB2Q8h/5w2KYVg==,type:str]
    ghcr_pull_token: ENC[AES256_GCM,data:nNKHq/Egj1BVN1SyB9zkg4T6mnjLAP37Ilzmg6NJ6Ds=,iv:jt0q9vRqY9YgoCfC8kl8rrK8tH9Ps+u90PvgJUHQyIg=,tag:3qILY1xvUSqN4NTOMQdL2Q==,type:str]
sops:
    lastmodified: "2026-05-11T05:31:00Z"
    mac: ENC[AES256_GCM,data:V7+J7Zq8DQLfqDTYYp0enwArclXcXUMWRX6Ys9Bi4hmVaCVytG0QWLqle5mc9VdZ5BjsunFMx1+q7Z5SvbqUD/kNz9i4TpRTzO+uBHrfWVjdHVdk2wJpYbSAEEwVwpVmvdn4XYxfLeA5Yt7JkDJVfikz/zJHEW8PkCsabjXMCoY=,iv:z/jdtfsiDuLLbgTIMbH+H6N2l/Y8cPooz0jbn1BSWsI=,tag:sKq6zRZMMuQFeivvU+hO+w==,type:str]
    pgp:
        - created_at: "2026-05-11T05:31:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAFJAh1BI0T/LdNxd3CIOvsNZd1QMcnqgUTWl4fFpGNxsw
            X4mWqzOkcthQkCcx88wnnO5Btv+pOQZJbu3KmMTRkLUxPzfhnkkrO4qV8llX/hxH
            1GgBCQIQ/Dv/lBo5/Ru9BVmXmSRPQhT0KBUQtEHf6MRoqLKtVs5QVzN7JG+2G9IJ
            0kn51TBOl1fMHqtXqbjLdQy1cmTWsQEA2s4U/uArZn0T4sE20XYtGgun/jKJXD0O
            ZDpNlv9+MtjBqA==
            =tFxD
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
