apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pat-secret
    namespace: github-runners
type: Opaque
stringData:
    ghcr_pull_user: ENC[AES256_GCM,data:RJsgbtpWOqcTDA==,iv:NKV8ZBIGhmOfOjDQZKrO72k2d3+BC9tCpX6DfGv+s4A=,tag:et+PMOUrnHOpKihP7rfkGQ==,type:str]
    ghcr_pull_token: ENC[AES256_GCM,data:Zh+whw7yLWcyH+RGE2ZA4/0+RK+r26t1LUC55u4MPWF6yrfZ3QS7UA==,iv:GesCtltpFe6WfwcjbCN+2wNShhmI5zvytdIviwdhvQQ=,tag:UbX9yxfw+6AIKoqRNKpYbw==,type:str]
sops:
    lastmodified: "2026-05-11T09:14:41Z"
    mac: ENC[AES256_GCM,data:8fSkQpE1ZUB3WlkhTjTUVMumz1kNKtKyBoca0KRxQ/15YSBPe4DkMYWyNAZ9F5/I5F+PJhdqR3LdyXa15/g8X0uVJM56VroK7DHp0EpqsrZcLdfhrTXmewiRgJFkKjjmfDH5AQkNHFCNySvi26RzqaMGTvOYOXPOcllLR/7QL98=,iv:P5m0vDBCydZcwossy1qw40kL6NmzxcMR6GC1tnlubv4=,tag:wNTYqztaPUlsfa6R5EcHAw==,type:str]
    pgp:
        - created_at: "2026-05-11T05:31:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAFJAh1BI0T/LdNxd3CIOvsNZd1QMcnqgUTWl4fFpGNxsw
            X4mWqzOkcthQkCcx88wnnO5Btv+pOQZJbu3KmMTRkLUxPzfhnkkrO4qV8llX/hxH
            1GgBCQIQ/Dv/lBo5/Ru9BVmXmSRPQhT0KBUQtEHf6MRoqLKtVs5QVzN7JG+2G9IJ
            0kn51TBOl1fMHqtXqbjLdQy1cmTWsQEA2s4U/uArZn0T4sE20XYtGgun/jKJXD0O
            ZDpNlv9+MtjBqA==
            =tFxD
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
