apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pat-secret
    namespace: github-runners
type: Opaque
stringData:
    ghcr_pull_user: ENC[AES256_GCM,data:QBxKyA==,iv:EpsREllL0f+yhXmVgeqXMP4lPDMrXAM8W4xOKdr6OQQ=,tag:nqIi1WigkDhB1HgxUstQQQ==,type:str]
    ghcr_pull_token: ENC[AES256_GCM,data:/RSysONBi0iUw3+6rTz/eXixEL4FJVJ/41oUFkLhTXT85P+cOnVc8Q==,iv:q2AeU0EDO58guRBuA4H/3b1rEJsq1jJB3RPo084EUCw=,tag:4UaWNzctZSz/5OsBogO7CQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T03:25:29Z"
    mac: ENC[AES256_GCM,data:KzQtACjakRtPLccMkuBr6EnbBxNA0kAcKYDwnf377EGtTY+/nlt4t+CpvE0GO+4uAKUZCgobQirrPNyRzitnYnGzTKBOxsKsLq+fa6IbXWxSJK8R7GWmmbRHn1fHaorhnTz+xqLJuhQ3+yWFvNrspU9UVES5FBxgSccHn++REMA=,iv:n7DfRcgjXndzw8jE6VxYQ6WFeCnS2OGtcW9p7ZjN3mw=,tag:OHSo6AGoewex2SBm5c6Z2w==,type:str]
    pgp:
        - created_at: "2026-05-11T05:31:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAFJAh1BI0T/LdNxd3CIOvsNZd1QMcnqgUTWl4fFpGNxsw
            X4mWqzOkcthQkCcx88wnnO5Btv+pOQZJbu3KmMTRkLUxPzfhnkkrO4qV8llX/hxH
            1GgBCQIQ/Dv/lBo5/Ru9BVmXmSRPQhT0KBUQtEHf6MRoqLKtVs5QVzN7JG+2G9IJ
            0kn51TBOl1fMHqtXqbjLdQy1cmTWsQEA2s4U/uArZn0T4sE20XYtGgun/jKJXD0O
            ZDpNlv9+MtjBqA==
            =tFxD
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.12.2
