apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jared@jared.kiwi.nz
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
      cloudflare:
        email: jared@jared.kiwi.nz
        apiTokenSecretRef:
          name: cloudflare-token
          key: CF_DNS_API_TOKEN
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jared@jared.kiwi.nz
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: nginx
