apiVersion: v1
kind: Secret
metadata:
    name: volsync-secret
    namespace: home-assistant
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:4YlM2NGkzDRlVBHlzLJ6ud4S5EOr4S8JowQmCw==,iv:Tfyue+3hO8JdGI0BMTCaUtSnogKrEQeuFzyj1785ZEE=,tag:LsrJwx81vaSopUbVvR3QjQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:Ps1+mty17paszPnqAQWCUqPz5zVe50vkflSuI9U19MIH6h+7f/fBG4Ea6AY=,iv:WP6GZGBhSL9PhVf/c13VY+u6knUIZZA4GciU78iaxZE=,tag:ddBdOHtu4Lfd0KQsMOo6hQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T02:39:23Z"
    mac: ENC[AES256_GCM,data:jpjrCpBJBSxrmzqehgh8NU99ea1ISsH0a1OarbDr2Jg0S6vKjVxIejOJw29QwiBo5qPZ7XhczJ5v4DLwyaLUQXyZk8dQ99VIroOamf0nAqFQyt/Ai8/iJDbfnYf0kTQWdcz8RipzYv15NDn4LBO+rDVoL7cIxrq9oWAylgoDic0=,iv:tg3smTOQChHzQepB72hD8cx9N27C1lhhylUefCnzSO4=,tag:/Wx8Z49F3KtojYkj0wE3gQ==,type:str]
    pgp:
        - created_at: "2026-06-30T02:39:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAooq0ZtLkZBbhjz5XVNeKcsVmfxJFOP9Sr3McObjr8wIw
            TjnpSDB7etqVKPnk1TQiP/iySXIhHtJ76ZrwhQNbKTi06c72PAGCELr5KYUWzCGL
            1GYBCQIQdChgiqc3t5m5c9OVHu2+lh6+QNYS0hB2yUw+ij9znJKtD5cf3BI2HI4I
            cpbwAezJlnEHo6fhVaPfZTzxBGs4mPEsCytqxA3a9Dbo72cOUyvcOsUGapSb5/x4
            3+dhvKezrxw=
            =BiJO
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.1
