---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      nodeSelector:
        gpu: amd-igpu
      securityContext:
        runAsUser: 3000
        runAsGroup: 3000
        runAsNonRoot: true
        fsGroup: 3000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44   # video
          - 104  # render

    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
            env:
              TZ: Australia/Melbourne
              JELLYFIN_PublishedServerUrl: https://jellyfin.home.lewelly.com
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 8Gi
            securityContext:
              privileged: true
              readOnlyRootFilesystem: true

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 20Gi
        globalMounts:
          - path: /config
      cache:
        enabled: true
        type: persistentVolumeClaim
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 20Gi
        globalMounts:
          - path: /cache
      media:
        existingClaim: media-library-csi
        globalMounts:
          - path: /data/media
            subPath: media
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
