apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      # The chart directory name in the repo:
      chart: home-assistant
      version: "home-assistant-0.3.9"                   # match a valid tag/commit in the repo
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system
  values:
    replicaCount: 1

    service:
      type: ClusterIP
      port: 8123

    persistence:
      enabled: true
      storageClass: standard
      accessModes:
        - ReadWriteOnce
      size: 5Gi

    extraEnv:
      - name: TZ
        value: Australia/Melbourne
