apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vela-s3
resources:
  - namespace.yaml
  - pvc.yaml
  - pvc-csi.yaml
  - secret.sops.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
