apiVersion: v1
kind: Secret
metadata:
    name: s3proxy-credentials
    namespace: vela-s3
type: Opaque
stringData:
    S3PROXY_IDENTITY: ENC[AES256_GCM,data:fDBlU+knRboi0rPhhauit02aNTKId7Yv6es67rdy2Ds=,iv:etPKJrEi2GdG4DEc3XaPsHp7YwMWpdRFV30f0Bbgxh0=,tag:Iu1U6yY4jpDsVQnjN55O8g==,type:str]
    S3PROXY_CREDENTIAL: ENC[AES256_GCM,data:vs7b4HtN95zOOjQXltqdZYufAab/HGenN3GoTzWXfx3bflEy4lpqJVAmmtFKF7fjthbDOVBPfc6d2+qoRJ1zWg==,iv:006lHLwD4EVmxPRWtSMvNje+bF5McxdAnkuplPsr4zg=,tag:m4GgiE0A3JfcW40eMnIzwg==,type:str]
sops:
    lastmodified: "2026-04-18T06:18:39Z"
    mac: ENC[AES256_GCM,data:yV0xACY9gofh0MYQbC0rbXjslPPpoUGRXELd4lzeq0m1T5P5NWAEwtWL2Vo0LLtSBfKi2atTcNgr6sy9LM1n7O5RGHMZLqUvnHS+L1ltI9rGq9Tqvue3+oEMpwq7DKvIPJnWmgRz20e28IimTfOIxs7/48zFDSs/KVPdtgh6wzM=,iv:WDJQnBhj5bh60ORnSaIZFIChUFKHRJYYS2dGRxjLgzE=,tag:Aj0fOf/69z+Ves2zcFJibQ==,type:str]
    pgp:
        - created_at: "2026-04-18T06:18:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAne1Y+er3ipdmkU5iht6iEgbP2EURxQmBYTXPke+Q+Dgw
            aiDgViaYCS5KTxSSa1Tn9Zl3tFr1AwNRyXsSmbD+u2Ovhhm4V8+m+AdwfkiKF0KK
            1GgBCQIQjfcle3IcgtmHUftUAdMngFYkTX3a16MvJCPmG+UeZYi0MZAcGuuXxiNV
            ZfzmtrBkeLW7RKEgH1bf03MK27+0RAia4b+zfQBHHfzm9DkRuMOIAqXjZWMpAJr4
            SgDgcse4W8U/sw==
            =ODhR
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
