# External Ceph Cluster Secrets
# These secrets are required for Rook to connect to the Proxmox Ceph cluster.
# Values are obtained from the Ansible playbook output after Phase B completes.
#
# IMPORTANT: This file will be SOPS encrypted. After running the Ansible playbook,
# update the placeholder values and run: sops -e -i ceph-external-secrets.yaml
#
# Monitor endpoints format: <ip1>:6789,<ip2>:6789,<ip3>:6789
apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-mon
    namespace: rook-ceph
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XXucM1KnU5wmk96xscm4g13ouyFuBIGBdfScmRFi2jiBl7o=,iv:GhqiXBpvQOj0fKoVIXGiNZzle5OB3BfSIhjexSmvc/c=,tag:1C+8f1yx0gYq3v7bI4zsYw==,type:comment]
    cluster-name: ENC[AES256_GCM,data:gd8WJQ==,iv:aCiAGnY/orGGF6/6WNReujTHj1d3guyLQL0EXUj9/ug=,tag:uuLtoYeEzmm9d1RqjBN9eg==,type:str]
    #ENC[AES256_GCM,data:pL9BuNbLmFee6LQZwSw0LrefZe4j7+rlG+ux4dp+,iv:+uj7SikrLnlusIJU21GZ7YeDOhRKjXlWHbYVPfzU86E=,tag:cWaZsjYnB9VGsVQH67TbIQ==,type:comment]
    fsid: ENC[AES256_GCM,data:n0yymS7dYduq58zRSxFIcecgAvmBSJRu9KLS7rWrKk/DaJVd,iv:mC1FTVFyqkThpcAf+Vpe+2ppIHE2YwYJmDU3VI4Hh2c=,tag:DFSnvIuTl5R7ltEq/uqy+w==,type:str]
    #ENC[AES256_GCM,data:bVicH+tTNKT169CktT0AOWppJiDkT1a8gBP3+W0=,iv:FAGEO049sYbZXmu6OgyMXyh0mGBtk9gW3S1dZHhvBj4=,tag:Nik/ZyI/r0RldcwBMOKxJg==,type:comment]
    mon-secret: ENC[AES256_GCM,data:UY/n+JnVp5cdaw==,iv:S9Y20iu+1xQ+CA33jVeUg3IFRIyFwUaAFfoiWt9JK5s=,tag:ZJ9TZ+6odjX3hcXHwR7LQA==,type:str]
    admin-secret: ENC[AES256_GCM,data:/oJsDaCxkDunj0cu1voaNfElnMyQtsuwfSTEso4c0NjdziBlSm853A==,iv:tWkrUEACWw+l63Ob6tgFlB7tB36m4ce3f6z2qBYIppE=,tag:ukkrdM3xAU2WozwVXDAn3A==,type:str]
    #ENC[AES256_GCM,data:OwFJqaliTyzVRHUPijsWsMZPCw1rcpQ7Pr4w4YQWO+AGwj2n2bvvim1MUCwX5kIIM+1wyeyPoG17I//OTYqMk8/5IrcJXgU=,iv:aloaWebOe810YB0NV7YvFavs/WNoLoggKRij1vgRQK0=,tag:dsxSyBZb0tPjbL7XWuOQuw==,type:comment]
    #ENC[AES256_GCM,data:AZzmTo9kcYcSwOgay/P1UoBps2mpEBKe209Ez8TezqQZZ++M25Nug0DNzOkYPyk8t5qsRAV3iOePjyAtbIaMIXtg,iv:WSBlpYZyJOKZQYlI3L9idl67NJSupgL5/QI9L8+mgwQ=,tag:tbjz6Evbzu6wl27SLySBAA==,type:comment]
    ceph-external-mon-endpoints: ENC[AES256_GCM,data:8HdlNVBeZie8fy+he5pm0GjgF55HBnKcOw1JyeBfoiq0iGbMRXS+jh1PUTMN58VoFv4mN3syJ3uw3Jq/YNCbG2hdUInNJ4HxTYZgEOhvrWPY2Dv4hVGOzxaA+n3YT8rJvkZOVaQzoYPROwaJv2eSVcuxSgBPi29b0Aqx0Qs=,iv:nV+ZI0HaOnbjMR3eWeE++g5pGAUUNbZCP+9DtFgV9dM=,tag:Vog55bhViaSWL87YNGcJVg==,type:str]
sops:
    lastmodified: "2025-12-18T11:09:11Z"
    mac: ENC[AES256_GCM,data:J0tT6B+vub4JlL6WROOzxKG2PrWZs/0Ci6/fV940Y9aeLj/QLrHXsTcXICN6PH+41HEVxoeDvIMqBuVpk7Fl0th18TjmkjuZuE2sQSfYwDaXJQm7xROjvGfiL2Cbcnu7Pf6xdP0rNFB4N62mqYR3nL44lujQYCx29uZPfiLdrNs=,iv:5cd7kBM41cBz8y73gavaLogHWGqdEePKKqBmdpUxYSQ=,tag:tDqonrbZ1uIm69m77Qq4Pg==,type:str]
    pgp:
        - created_at: "2025-12-18T11:09:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAZb6M8m4jvXq2X/wDqC359w35OpJmijzTKLeIlEistQQw
            a5yp3NyBf9/55zDNWcQOVtCBvXywIUZiLigGkeLY6W2zSYBFOxDMY7UZfDRAEyvE
            1GgBCQIQ5IWiUJaPyuic2lG8OOVWn7wI2l9XIYCQca5IluM64ZpwsmvcFF8FU10H
            lu3u46RYiPQTJSyr99S+119UEwqSJX7tdeT1pM6iIgBGVirROlnXY0t7hBqotxkS
            VmU8lvShyF/I+g==
            =s1/z
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bRwZSPd4u6H2igKr9L5RL/sUkj9HPps7NgIRKJL9l7n2C2jxhZpPUJQidgdaBvkv,iv:EzsO4qJ2zAzvDZhUBwUgs0YnsoRU4aGkFPXJfoPafRg=,tag:aeeuKCvRRTGvfr6tKD2TgA==,type:comment]
    userID: ENC[AES256_GCM,data:oQxOePcKYRJtvw==,iv:J4vDOlW9nDwvFKA1Q5Kn8XlT9CAQgd9H3oF7clwO/2I=,tag:2mlTfJ3AOhOdufZCIv/XPw==,type:str]
    #ENC[AES256_GCM,data:NilnWHq3TdaxLpRUWMIa+TMbLxhH20pr19ghdSG9Ttrw9rfK6A7LJ7anVpSD34yOFcbEYQgThHKO8U2OpE5EFK7QZw==,iv:4AHeR85gQFAZbfLRB59MW1oWnsmV1/lV/IoWT6B88iQ=,tag:Ic7xg33WxgwcgWqHJkZREQ==,type:comment]
    userKey: ENC[AES256_GCM,data:byirxQYK5zec/dNtPSYnKiO8ZbscS9uc35pFG2GRyH5sTejW1Qjg9w==,iv:exoOlkZnvko5sl3A30Bla7C+xtgzHmH/VMAgCB5Z7/g=,tag:eJatDiguBB6jvQSnBhGHNg==,type:str]
sops:
    lastmodified: "2025-12-18T11:09:11Z"
    mac: ENC[AES256_GCM,data:J0tT6B+vub4JlL6WROOzxKG2PrWZs/0Ci6/fV940Y9aeLj/QLrHXsTcXICN6PH+41HEVxoeDvIMqBuVpk7Fl0th18TjmkjuZuE2sQSfYwDaXJQm7xROjvGfiL2Cbcnu7Pf6xdP0rNFB4N62mqYR3nL44lujQYCx29uZPfiLdrNs=,iv:5cd7kBM41cBz8y73gavaLogHWGqdEePKKqBmdpUxYSQ=,tag:tDqonrbZ1uIm69m77Qq4Pg==,type:str]
    pgp:
        - created_at: "2025-12-18T11:09:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAZb6M8m4jvXq2X/wDqC359w35OpJmijzTKLeIlEistQQw
            a5yp3NyBf9/55zDNWcQOVtCBvXywIUZiLigGkeLY6W2zSYBFOxDMY7UZfDRAEyvE
            1GgBCQIQ5IWiUJaPyuic2lG8OOVWn7wI2l9XIYCQca5IluM64ZpwsmvcFF8FU10H
            lu3u46RYiPQTJSyr99S+119UEwqSJX7tdeT1pM6iIgBGVirROlnXY0t7hBqotxkS
            VmU8lvShyF/I+g==
            =s1/z
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: rook-csi-rbd-node
    namespace: rook-ceph
type: Opaque
stringData:
    #ENC[AES256_GCM,data:W61iSkgjHglvC6P/uaRoAXThUcxN3/xc0r+HxTntbzKROB7lE7gPHODm6sUGPxXa,iv:jYaCQJ6FM0lB0YQiiDuS7RN5r6rWck5A8tsF6syk0tI=,tag:X4wtRHPD4le+xKYJygGjLQ==,type:comment]
    userID: ENC[AES256_GCM,data:m+mlyAoITCNEcg==,iv:1LPa30QosKX4GV5amshfbmfVn0R+zpAm07yHX68de9Y=,tag:iVqHiZaUg3uEAD8AKCwlxw==,type:str]
    #ENC[AES256_GCM,data:vmtIACaOIryOHxF0zoyg57oYLeR5PCDv,iv:0vT9hg8An9W9y0Xv2TdifalCrv6gsPdeOAeUqcLKLWg=,tag:9QrvmvLZ5mDmDVEQUtKtvA==,type:comment]
    userKey: ENC[AES256_GCM,data:c1+qYCn+w8DW0BAk/AHSg/Xrixe7xCYJcoLX94O0sWt9o0THXhFPkg==,iv:Ps1o9SZoC2U4bx29UaegtqdojTMIilL4zSFhjT/wP4Y=,tag:deyeMi4XVIpm0QygSjlvcg==,type:str]
sops:
    lastmodified: "2025-12-18T11:09:11Z"
    mac: ENC[AES256_GCM,data:J0tT6B+vub4JlL6WROOzxKG2PrWZs/0Ci6/fV940Y9aeLj/QLrHXsTcXICN6PH+41HEVxoeDvIMqBuVpk7Fl0th18TjmkjuZuE2sQSfYwDaXJQm7xROjvGfiL2Cbcnu7Pf6xdP0rNFB4N62mqYR3nL44lujQYCx29uZPfiLdrNs=,iv:5cd7kBM41cBz8y73gavaLogHWGqdEePKKqBmdpUxYSQ=,tag:tDqonrbZ1uIm69m77Qq4Pg==,type:str]
    pgp:
        - created_at: "2025-12-18T11:09:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAZb6M8m4jvXq2X/wDqC359w35OpJmijzTKLeIlEistQQw
            a5yp3NyBf9/55zDNWcQOVtCBvXywIUZiLigGkeLY6W2zSYBFOxDMY7UZfDRAEyvE
            1GgBCQIQ5IWiUJaPyuic2lG8OOVWn7wI2l9XIYCQca5IluM64ZpwsmvcFF8FU10H
            lu3u46RYiPQTJSyr99S+119UEwqSJX7tdeT1pM6iIgBGVirROlnXY0t7hBqotxkS
            VmU8lvShyF/I+g==
            =s1/z
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
