apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: rook-ceph
    - name: ceph-cluster
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-kube-prometheus-stack-operator
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-prometheus
      namespace: monitoring
