
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pajikos
  namespace: home-assistant
spec:
  interval: 5m
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: home-assistant
  values:
    replicaCount: 1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: ha.home.lewelly.com
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: ha.home.lewelly.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: home-assistant-tls-secret

          hosts:
            - ha.home.lewelly.com
    service:
      type: ClusterIP
      port: 8123

    persistence:
      enabled: true
      storageClass: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    extraEnv:
      - name: TZ
        value: Australia/Melbourne
