---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-claim
  namespace: home-assistant
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnly
  resources:
    requests:
      storage: 5Gi
