apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack
    namespace: monitoring
type: Opaque
stringData:
    webhook_url: ENC[AES256_GCM,data:seEf3hmD6CzFKXqPfnJ9HEbfULZA0zjCPzoYoSLKTC7SLLsG2EL/8Ixu0eGOUA5QGJD/QLs4goT+B7UFHbbAukU+ISb4b2OfKjY9KoWoNQsc,iv:4Tkia3l2+KycwBZC7DGrALjGT8EKYMPTNYqbNDs3p9o=,tag:iMw5RhgsSR9eTJwWq+VRfA==,type:str]
sops:
    lastmodified: "2026-04-14T06:05:26Z"
    mac: ENC[AES256_GCM,data:Rgv/FqHYaTevwn6zEEpAn1Nst/zXGQTQijy+s/tQ5gX8hcdSqoX1NcZWtGNUoK427puJheH/PkbATu16l9wSLEqnh5HoBo2gBbTUY0cx0tRzR/j3PN+8tRtOaB4Qw/J4A2nWwkjBaQG0FrbqQeCGsVgprYsFE5LkpsfJ96eniuk=,iv:n9KmWPuPak8nUwVjADBl3XNqLJlaeip+G5LndhmDD9s=,tag:GeY1yL+seO9vTRE9SKLpow==,type:str]
    pgp:
        - created_at: "2026-04-14T06:05:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAYmcjmqDpB6TaAz4X6wpzRlmOHqHhZ+4sqTZ0pYJj83ow
            iPhrsyfDkxEi5f3wiXQi2Jx6z76Mz+hKIpboWJ9LZbVkLG+dPjn8l1AgY7tYrCQk
            1GgBCQIQnzv5XHbs37AVMJwwEVLjZfTxEb3Ao4IlwBi1gL9GnC7BvfbBUbFmGS+8
            fs7He+EnojPQfUrrwxtitsxclegEOkqQ2HpHtPSd1c64n9n9mOotZzGwwQoKnv9O
            fFtZII31dIAnJw==
            =anoM
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
