---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: climate-ref-flower
  namespace: climate-ref
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/component: flower
      app.kubernetes.io/instance: climate-ref
