---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: climate-ref-flower
  namespace: climate-ref
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      metricRelabelings:
        - sourceLabels: [worker]
          regex: "celery@climate-ref-([a-z]+)-.*"
          targetLabel: provider
          replacement: "$1"
  selector:
    matchLabels:
      app.kubernetes.io/component: flower
      app.kubernetes.io/instance: climate-ref
