apiVersion: v1
kind: Secret
metadata:
    name: date-jar-secrets
    namespace: date-jar
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:nJ1+F6Hkm5Nh15NBz0k8VMGp/jDwWcE4ERuA02/y1eH69mURzYQeMaXo0CU9uqdDFKiLXb9yQ4l1nCpmd+YTDA==,iv:uDJEPDMOwaQ6i4Tl2D1YvSFOjrLWWpSaMcFfEK6fxLk=,tag:C+knnC5deYAUr+sHfViSAA==,type:str]
    AGENT_API_TOKEN: ENC[AES256_GCM,data:jzUZpJe3eaS/BPMdyoEHYif/DG33x7YHdQtfbvlzS6bSzoRKOdzTtIhmsCNvMgliwZqKqYJabE3EnR6EYkbChg==,iv:GPwA2FQ3Hb3ccVSeYtFS2PktOnOuV3SoZE3ihKLYkRs=,tag:QuBOpXduLnxBLAB9rQdWNQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:fSFC7CBbGE093RVmR8mmsiaQi8SoU/T2e23WIOcshw76ErkhWkBPbWb8VWM0cGWX6u8tEz63R6BO9hNihlv14w==,iv:b2lWzzqfIvLfZXcqkuRIVpa1GEDLudC5T/DH4ofTydo=,tag:Ze3wkmedjB3I0m2tl1pwqg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:pZyuP5wrlf8a71gnTcP8p2cfkirT7SqEhX5w9GMixXuNS7lLEx0qBrTLsEDhLJP02n4DW+PJqRKRTTyQBgQMUT4jtde+zVEjnurvy5w36US5EdiOFvAb2Svgj/bksxaYDwPIII1JridMDEVLnS4H10a+lp45RIbFVnOEljoK5QaWNJWr7/8SV9tAjNLX/CQ=,iv:tPzF08Y38uNsOvqil8W8nxTRBZGuhOmx0U8WMG80vc0=,tag:8NkEgH99HWltXzD3LOgl2A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T07:13:57Z"
    mac: ENC[AES256_GCM,data:xHpMkhKfrPdgJX2feQ7EUH0EWoI4l89UaRVVQJNs4LnzB6emMil7qf/5AO75ConPdI7d89sifzAH0d8Ir4XJ7/GF1nKc4LI69Ma+NHvmPXGuDcWZn1ITnAtXG6bDjGx0tZLW/7LyLREJH/TkvgMsmeI5Og2WwWflEP39JTqVm+g=,iv:p8BDLMcpUY0f+kGZ68mofkXr9FrEE4eDoSoeQsAwsdw=,tag:DD6vlJsVCIt7zyM0Ctxneg==,type:str]
    pgp:
        - created_at: "2026-07-11T07:13:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAT9QNu0MpvjUzghfOiys3kSh6Xt8QRRjWHnAxM3ak5Bkw
            KoODmjvAoJp0EVYk1m+Dn9LVDB7O3QR7ak3PW2kycw2Zkr6xnnKIMuahuzV7jMkr
            1GYBCQIQUFyVufhgkt+RJ6jqEbfBTn+aqhU8asb0z6YwXWW82pkpeRXBNREL8mME
            /6lj4FtTL5OoX6njBYbAw37ExsSW6am2YRvW4Q0/GVjTf40vaKVz+VSnNJ2RHysE
            MkiToiC661I=
            =s2j2
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.2
