apiVersion: v1
kind: Secret
metadata:
  name: date-jar-migrator-password
  namespace: date-jar
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:HDt6QbfWfjLdDnzhTTfs49ZmzAf8Vz9wbK5yQUl0HnnglAdWQ7hvCDh06NfhWoWq/hFrM0aCExE1qmRgjU6WXZkM4GKfJqH/ZXK8E8pioOusqbrbd3QwC+ktjVrsVBvV3di2zySATtqklWRxzuVypQ7SmWAuovbeWD6fyNBhTIGb0ltNXZ3fqINXunrHweM9yvwv1w==,iv:AWNWXR1upM40vXivyzNQ6aKX1/3p7N8MmdXVlmiwY7U=,tag:2JZv24Ouhl2liaQTQrZOOA==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T07:13:57Z"
  mac: ENC[AES256_GCM,data:7L0KQOJ9r7ZT9nn7gpQImECx0NSXujYK9ROsnIU3GS1NiG/O0i78OKBxjfSH8K8xtL8ZPh3TE1UWfRdHy2qdYDxGWQMb5KwydOIPM/WiR3S8FxWtqLwrr/fHWsQervcQcpxPu3wc/vfCUR8gLIyevxjLvif+uRAtiuPY2Z1bamE=,iv:NYRaxsBCIallm0QHoWluCmBQTzazIGYwPYl8kOaUmcw=,tag:yPiwlR9L9VqiMfF9odZVuA==,type:str]
  pgp:
    - created_at: "2026-07-11T07:13:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAQJbGa6MprIrt3vxwy+nnTBQ6EREwhmJl1jxDUTFSdGQw
        hChnCC0oldsDO8P7NlH2eLTv+aGwNnIo8FB1jj0Q21/hHl9/3YmkrGqksEoKt6ft
        1GgBCQIQfEybwxU/10gVsMyjZbGvPvp8Bv0J/hM2xntBCroeBTg2Bh4XCtYNJlSg
        /R+WBeY8Py5eu78KTiz8z/pG+fZyMwBQUWFvXhIZufVfdyyCnWo7F0KZEGRTb9HW
        TcVJAAY0JE4Xqw==
        =3qGf
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  version: 3.13.2
