apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: date-jar
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:0+22L2xaU9rLO3uSqD/6q+0agLQthknqFNUGeeYaDzXwq9GYC2h7sXgMmPTM/F+7GPSki715zQaDVw4HtmYW3Bf8L1+chzNhjjl8Uq9sZun/V+7Y9fCUUGNVIC5aU4Ekv7bg5XrbXYJzKv+HGYx8m7xk2MQfa/zmJSVFSRMEwjWV3qQHVS+ViA==,iv:1cRhU76icy9uhylHIWTVid07jXhGMBsBDwUx6IEV8xI=,tag:9hTpOSokgMMP9vRtPAmE+Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T07:13:57Z"
    mac: ENC[AES256_GCM,data:GL7xHJwS/RsmXFSn2gdk1gqKG6qnkKzEh52CCnmt49sKzhEh+d2q5B+bZfqXAnXOl4SBcjAtbmXU+whg/lrjhs02YgHPkArEeDLSWYRMr9fIr9SsBQF/NuA4lACe17GpgzcZhsBFgnojVoivGDBgl+tln7Sei7NZcQHXKtjZWFk=,iv:A75hVKevLSgyRwgzjnLH7Y18aK7Fs8coXoebDVV2XdQ=,tag:8OIPLwGTbfEmsSOfSvD3Xg==,type:str]
    pgp:
        - created_at: "2026-07-11T07:13:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAYfACdymlhU47I6+4n/rPKXmT6W9UPkMqWsOSHr4LNxYw
            vuJ0CdkS3Ezr251NqCr5Urn70T1JeqXZxe9rajHhDdNhmZyNbtHBfSqSNWQEMVSJ
            1GgBCQIQgok4wGPegVcvjo5/HR0HQedzkAGTLK7vhfHMSzpESZwmAmSx0wmEZc+1
            Y+LhdeHSjh64QRcq18FvwX9m0PouwNHl54xAfwNwDup1OpCApDFlV6NAOasz/sxN
            0kX676wMPGL/bg==
            =T49+
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    version: 3.13.2
