apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: date-jar
resources:
  - namespace.yaml
  - date-jar-secrets.sops.yaml
  - date-jar-migrator-password.sops.yaml
  - ghcr-pull-secret.sops.yaml
