apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc/
  - controller/
  - cache-server/
  - runner-env/
  - network-policies/
  - runners-ref/
  - runners-vela/
  - runners-vela-small/
  - ghcr-token-refresher/
