apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:YyIvNAq5hDQ=,iv:xIF9kO5r5AgKJ3SWkhBPnh9czFomAwWWnx8lN4gryP0=,tag:a6c+0LOIT/4S8hCATVxY3w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Q8SP6Xb2ArS0/5nU8jRZNivhH75h3VHvGBAECUKJ5iQgLEcfQIRn2WSs8ekHi5VvDR9dZPiluzeoLLMONJ5oWQ==,iv:DC7TdqhXr6ektDga19pGLn5r1pHsR2UvpW4NKTgn1ro=,tag:YlpLsZyuTCE61RvJMv8VSQ==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:mcGfcN/vv7DbfY/VNldMioUnoXb/EZWreorQh1w=,iv:f7iYck7JrtnsymtUdYJYapItJs46fmkwuvr1VCL4fTM=,tag:6SN8xkawbZJ5gIeSoFKnxA==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:Fli8f54SB36+/78JCC6oRuw9S7EMhNu3oJ9R,iv:ZWa6iP0RSYkHv0BzYaOHxSR8tWJm4UfiQkFeo34xAKU=,tag:+OcUHfL7uwooBPDvhxuzSA==,type:str]
sops:
    lastmodified: "2026-04-09T04:21:11Z"
    mac: ENC[AES256_GCM,data:jiqK4eMhU1eA4ij61NRAq614t7nfAbEw1Y+w15tB0Z+IrySgKmtJDK1ZsQ2XnlFNvkO7USzLqrhi6EBm3tuWcnyCXdkyRC3f8Y3JxZDMUd+IUeEmQCRgK67qb8ksSK58MfRICiqNkZXvfh6IvP5FzgjGfB6fb4mJGsDh3hdMgcs=,iv:3ksnvEgrPkSG+6T6YghBnWMrKzJfQVIF96JMlpCJqms=,tag:pDSmVCSbD5rhTJAapB4VNw==,type:str]
    pgp:
        - created_at: "2026-04-09T04:21:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAEGv+1tVcAR7GF6MhdbiUcijdMFtQhWiRN1md6T1x5xsw
            Ier6H/Th1he0eVgUDFhXjJ0GbK2xvT1kEZSY0jfVZ/LAyKx0I1TqcV2uARamsXxv
            1FsBCQIQ+jROcwBevduF/KfnMj0gC8IjwpBZUFx3WzV4RBdu/cKu1QHZxWTKxC7B
            cRRb91Vd3XRWxJaAoxXulb64CcsH2kdsaUQvff1GGJ7Ts8qciuHqd6yXCuK0
            =Ke9p
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
