apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Hi4JDjGrs2c=,iv:HzVDibwbA8GHtxCPmdFQVDk5NbyNlK6+7be0YQ0Y7AA=,tag:J/lYdpKSWXMdn9uy3wqKSA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:OXZwDpI4+CdEKQo1FddZ93xwW1M/R8pPUjsS7lxVckRsTUrpyfbrZCDSJYY=,iv:nXyZdZ0/fhnUOQvgXskO2+wSnLN2679onooyGacRWe0=,tag:p+bE/1+gd3sTDIA1QRz7ig==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:5BdDTkuGjc4AsAoCwOZajDI5fGYHZeMbgdrbKwM=,iv:ghRyiqSlHlCewBobTPB1DaDSFbBLy/XLIj/5fdVy82M=,tag:DSvQ1pzyD7df1KlfkS9msA==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:ZtN4nAVu30kbhc++AA8UYp62sNc8qTvbq1je,iv:8jJSJNbQaNTjCXDZLxjIX7wqxzagBDrbNyqNQkLu/nM=,tag:2lPj1SFFwPlTDsTkYZ9/qg==,type:str]
sops:
    lastmodified: "2026-04-11T08:53:19Z"
    mac: ENC[AES256_GCM,data:D5ggXXc3Om8MtO2sIUjoU72adA5E+xR1yAWA2YDEGTOvv7qYE1CgMy21O9BufpU5ezG8n11qojHgNT5k2NZzd3QvrKu3UGdWxjX71AVSdjz3e8Pk8hdyNWAvoJYEM1n0Aw5XTS2h3gMGtHpP0M7NawseF9V0JJo34jhJRBabFD0=,iv:MW6W9Rd++b/MZq+sywbT5RLYtKpq4srSbhT17NpSK5E=,tag:M3NMMxhU+eeA93aWFMgjzw==,type:str]
    pgp:
        - created_at: "2026-04-11T08:53:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAgOGdIOe4vHuLGEgeNI8mpFtKnmMW5gGJMquVyPQI4SAw
            dh7/GHhnW3OXuz63cE7cJ1QlJJ0F+PVaM8XwFFT+I2DNYVTxCwHQRnUAEqY13N/C
            1GgBCQIQO0XsEhFd3Rlr0ldqfk4gxkcuCpZlB7VEtkZXWcj3M7jm/B3jFG6yMOoI
            WcHJ72ZCK8O5902IoW3wOmotfP/fDHTaQ6VFwuGz/hTEaZDCqX2Wa9Zeqv0C0x9c
            Cd8e6y1LbbGzxQ==
            =1Z94
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
