apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: headlamp
type: Opaque
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:QCqfOP2BhDE=,iv:3XyjEfLinRjrl/pl2sYWUgPMWJ4/7aljp/ZYid+4TbE=,tag:p3X6hii3HqgvwDIaEZxDXQ==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Bm/b5fYl1rtoOmCEf3IbXy7TVvnwkDfff7M5JToiD0NEpLcyKec6M+PEKuQ=,iv:kavs20Ecdieb5YsqcK9FBT/CwPpk0KnYoStQ2yMGJ5k=,tag:HM1IlGvLMh4Qf0kiq+E+8A==,type:str]
    HEADLAMP_CONFIG_OIDC_ISSUER_URL: ENC[AES256_GCM,data:l64CxP7jkJ70imdF6li3TmmyqxsR9YvFkdVXbmQ=,iv:dnQIv9rPcAiycj37z9cPrRRP0c7zTYBuIGJ8RLHKRWo=,tag:HlC/UEV41CSZd1MoYXKDUw==,type:str]
    HEADLAMP_CONFIG_OIDC_SCOPES: ENC[AES256_GCM,data:sFSwnsQiNYhvwivZzdyFH7vrWnW/4ILuc1HO,iv:LBd7h+KRaKZccPCdoM/bzqMC1Bhfh9OsAcOPJOfIBdI=,tag:WcCzGi6lYphKpPsmpjrHQg==,type:str]
sops:
    lastmodified: "2026-04-11T08:33:08Z"
    mac: ENC[AES256_GCM,data:xBNQ4VPvjNkGqH2vBwoX3yBBXqtSAz0gEg+fN8nafqBmj0FInHPyb3TntI5UwkUIqqUXvWGb2BAnqEULfqxdvenk2zJ+Hy7iMMPXmrYy90dN83L15pkDQghOS7VHSHQHUL/D4sAPnREJYZGdM1rltxm2CPtn9kFvR/8rs3jyiss=,iv:kz2CZTL+QXmSWYlETz+TgcPqetZH3hbnBZ5+mEjMMcw=,tag:6Wh4jBHBIKc91+b6LjL/Ig==,type:str]
    pgp:
        - created_at: "2026-04-11T08:33:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DG75A0M95pbgSAQdAP0NM3tP2sfCrVBbefaswr61XkIuMETsXL6tY7b1xOS8w
            VgDiNU2kvVuml6Mj7z2FpoqkBPOC+oARO6TjEuazzA+3Ruh+k911dHpj5FTyMn3V
            1GgBCQIQ7xr8r0pD5WJkjkSTe9nZXpkenHrtPwWQX6rPa9SMIbhGLcrRYNIWqvFI
            Cm//BP6bQMlpr16MDoQIqlompRiLJMewPtUau3xzfafuTJw04Y/YVSWLG/VO6mLt
            GOTHd4eKOd0fHw==
            =pVE3
            -----END PGP MESSAGE-----
          fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
