---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: ">=6.0.0 <7.0.0" # Pin to v6.x (latest stable)
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  # Installation options
  install:
    createNamespace: false
    remediation:
      retries: 3
  # Upgrade options
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  # Rollback on failure
  rollback:
    recreate: true
    cleanupOnFail: true
  # Values override
  values:
    # Deploy in single binary mode for simplicity
    deploymentMode: SingleBinary

    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

      # Persistence for Loki data
      persistence:
        enabled: true
        storageClass: rook-ceph-block
        size: 50Gi

    # Loki configuration
    loki:
      auth_enabled: false

      # Common configuration for single-binary mode
      commonConfig:
        replication_factor: 1

      # Storage configuration
      storage:
        type: filesystem

      # Limits configuration
      limits_config:
        retention_period: 30d
        max_query_length: 721h # 30 days

      # Schema configuration
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h

    # Monitoring
    monitoring:
      serviceMonitor:
        enabled: true
        labels:
          prometheus: kube-prometheus

    # Gateway (nginx) configuration
    gateway:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    # Disable read/write components (using single binary)
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
