---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 3000
        runAsGroup: 3000
        runAsNonRoot: true
        fsGroup: 3000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.5
            env:
              TZ: Australia/Melbourne
              HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.media,
                sabnzbd.media.svc,
                sabnzbd.media.svc.cluster,
                sabnzbd.media.svc.cluster.local,
                sabnzbd.lewelly.com
                sabnzbd.home.lewelly.com
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
      data:
        existingClaim: usenet-downloads
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
