apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
  namespace: media
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:kc798HrSFjiMMz95di+0fBKqUrQ8CIG6cwY7i0L2aIc=,iv:dulK0QtM8f0Dde46DNbBzABgt8BayGW6JUKd5EGpPvw=,tag:h+CSRBaQnm5dTAO7wBPVtg==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:kGpOnTeRPZih6oUWMVGuPURjemITu0DiqkYV4L9yx9Y=,iv:6eXunJXHALYi6lKP4KiBzehVYz6ymJTKN7aByER5uDk=,tag:5ym5jt1TQb620yCqPl9yVA==,type:str]
sops:
  lastmodified: "2025-12-25T09:17:56Z"
  mac: ENC[AES256_GCM,data:3MyS0z5Z4DzEcXgaXtDOzw3Z9t/SMFAzUbJnulNu08+D29RWDFKh/SHHjEO4GOjHMGZFqk/z233+fL41zjaiHXiNJE00fFcsnxwvFxo+VvDHIhr3dZA/7S1dYHUVqjF+ykHC/YrKJ9Y8NjnZodSUcXAezZcnMb3f+iwXKAQ4M+Y=,iv:ZsjS+eeM1YIhHFF5yH7zg92JKlafPvo3Cgorv9eWtSs=,tag:G79yTocgo2vVD+Wu304wLQ==,type:str]
  pgp:
    - created_at: "2025-12-25T08:52:08Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DG75A0M95pbgSAQdAuxglxk1Cf+c6qipykUDhY51y2iSRsi9zSrGATlohI1Qw
        +3syZqQH5ApZRfhnts3LkkGy4P1COzqVmqW5nVGqr789DtU4jyjg5EfCU7F+au4s
        1GgBCQIQq9RcON6GkRvAIaGJ809XpT/sPlHzh7zZipQzyoYDWU6E1d3daZqy9Sfk
        vt5GvwQwipucZHC3mDhhnylSkjrh6nBejValOu6z3dnESXuf1oeNoI/X6IdMoYha
        KvGdCRLAYKtj0A==
        =iMrL
        -----END PGP MESSAGE-----
      fp: 069DD0015041A4D8B4FBF3C9848F5EA65E3CFB0F
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
