apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: reloader
spec:
  interval: 1h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 1h
  chart:
    spec:
      chart: reloader
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
      interval: 1h
  values:
    reloader:
      watchGlobally: true
      readOnlyRootFileSystem: true
      deployment:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
